export type PromptCardDifficulty = 'Starter' | 'Intermediate' | 'Advanced';

export interface PromptCardInput {
  readonly label: string;
  readonly helper: string;
}

export interface PromptCard {
  readonly id: string;
  readonly title: string;
  readonly category: string;
  readonly difficulty: PromptCardDifficulty;
  readonly description: string;
  readonly useCase: string;
  readonly whenToUse: string;
  readonly whenNotToUse: string;
  readonly inputs: readonly PromptCardInput[];
  readonly promptTemplate: string;
  readonly outputStructure: readonly string[];
  readonly reviewChecklist: readonly string[];
  readonly expandContent: readonly string[];
  readonly exampleRun: string;
}

export const AIBI_SAFETY_NOTE =
  'Do not enter confidential customer information, account numbers, or nonpublic personal information into public AI tools. All outputs should be reviewed before use.';

const STANDARD_REVIEW = [
  'Confirm no confidential customer or account data was included.',
  'Verify facts, figures, policy references, and dates against source material.',
  'Mark assumptions, gaps, and unresolved items before sharing.',
  'Have the accountable banker review the output before use.',
] as const;

export const PROMPT_CARDS: readonly PromptCard[] = [
  {
    id: 'ai-task-framer',
    title: 'AI Task Framer',
    category: 'Fundamentals',
    difficulty: 'Starter',
    description: 'Turn a vague AI request into a clear banking task with context, constraints, and review expectations.',
    useCase: 'Use before asking AI to draft, summarize, analyze, classify, or compare banking work.',
    whenToUse: 'When the user knows the outcome they want but has not structured the request.',
    whenNotToUse: 'Do not use for final credit, legal, compliance, or customer-impacting decisions.',
    inputs: [
      { label: 'Role', helper: 'The banking role the AI should simulate.' },
      { label: 'Task', helper: 'The exact work to complete.' },
      { label: 'Context', helper: 'What the AI needs to know.' },
      { label: 'Output', helper: 'The format the user needs back.' },
    ],
    promptTemplate: 'You are a [ROLE]. Using only the context below, complete this task: [TASK]. Context: [CONTEXT]. Constraints: do not assume facts not provided, identify missing information, and separate facts from judgment. Output format: [OUTPUT FORMAT].',
    outputStructure: ['Task summary', 'Relevant context', 'Missing information', 'Draft output', 'Review notes'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add a risk rating for the task before generating.', 'Add a validation step for figures and citations.', 'Ask AI to produce a short audit trail explaining what it used.'],
    exampleRun: 'Frame a branch manager request to summarize a new procedure into a staff-ready checklist.',
  },
  {
    id: 'better-prompt-builder',
    title: 'Better Prompt Builder',
    category: 'Fundamentals',
    difficulty: 'Starter',
    description: 'Rewrite a rough prompt into a complete role-task-format prompt with banking guardrails.',
    useCase: 'Use when a banker has written a basic prompt and wants stronger output control.',
    whenToUse: 'Before using a public AI tool for a non-confidential work draft.',
    whenNotToUse: 'Do not use to bypass approved systems or data handling rules.',
    inputs: [
      { label: 'Rough prompt', helper: 'The original user request.' },
      { label: 'Banking role', helper: 'The perspective the output should use.' },
      { label: 'Required format', helper: 'Memo, bullets, checklist, table, or email.' },
    ],
    promptTemplate: 'You are a banking prompt coach. Rewrite the rough prompt below into a safer, clearer prompt. Include role, task, inputs, constraints, and output format. Do not add confidential data. Rough prompt: [ROUGH PROMPT]. Banking role: [ROLE]. Required output format: [FORMAT].',
    outputStructure: ['Improved prompt', 'Why it is stronger', 'Risks reduced', 'Remaining review steps'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add a scoring rubric for prompt quality.', 'Add prohibited data reminders by data tier.', 'Map the prompt to “structure, generate, review, refine.”'],
    exampleRun: 'Improve “write me a board update about AI” into an executive-safe prompt.',
  },
  {
    id: 'output-quality-checker',
    title: 'Output Quality Checker',
    category: 'Fundamentals',
    difficulty: 'Starter',
    description: 'Review an AI draft for unsupported claims, missing context, weak structure, and review risk.',
    useCase: 'Use after AI produces a draft that may be forwarded, edited, or relied on.',
    whenToUse: 'When the user needs a second-pass quality review before using the output.',
    whenNotToUse: 'Do not treat the checker as approval for regulated or customer-facing use.',
    inputs: [
      { label: 'AI output', helper: 'The draft to review.' },
      { label: 'Intended use', helper: 'Internal notes, customer email, board memo, procedure, etc.' },
      { label: 'Source context', helper: 'What facts the output should be based on.' },
    ],
    promptTemplate: 'You are a banking quality reviewer. Review the AI output below for unsupported claims, missing facts, compliance-sensitive language, unclear recommendations, and formatting problems. Intended use: [INTENDED USE]. Source context: [SOURCE CONTEXT]. AI output: [AI OUTPUT]. Return a review table with issue, severity, why it matters, and suggested fix.',
    outputStructure: ['Issue table', 'High-risk statements', 'Missing information', 'Suggested edits', 'Use recommendation'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add severity scoring from low to high.', 'Add an audit trace column.', 'Require every factual claim to map to a supplied source.'],
    exampleRun: 'Review a draft branch announcement for unsupported claims and customer-risk language.',
  },
  {
    id: 'risk-control-mapper',
    title: 'Risk-Control Mapper',
    category: 'Risk & Governance',
    difficulty: 'Intermediate',
    description: 'Connect an AI use case to likely risks, controls, owners, and review points.',
    useCase: 'Use when evaluating whether an AI workflow is appropriate for banking operations.',
    whenToUse: 'During use-case intake, policy review, or lightweight governance discussions.',
    whenNotToUse: 'Do not use as a substitute for model risk, legal, or compliance approval.',
    inputs: [
      { label: 'Use case', helper: 'The proposed AI-assisted workflow.' },
      { label: 'Data involved', helper: 'Public, internal, confidential, customer, or NPI.' },
      { label: 'Output audience', helper: 'Internal, customer-facing, board, regulator, vendor.' },
    ],
    promptTemplate: 'You are a banking risk and controls analyst. Map this AI use case to risks, required controls, accountable owners, and review checkpoints. Use case: [USE CASE]. Data involved: [DATA]. Output audience: [AUDIENCE]. Constraints: do not approve the use case; identify questions and escalation needs. Output as a risk-control table.',
    outputStructure: ['Risk-control table', 'Control gaps', 'Owner recommendations', 'Escalation questions'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add control maturity scoring.', 'Add policy mapping.', 'Add audit evidence needed for each control.'],
    exampleRun: 'Map risks for using AI to draft member complaint responses.',
  },
  {
    id: 'regulator-lens-review',
    title: 'Regulator Lens Review',
    category: 'Risk & Governance',
    difficulty: 'Advanced',
    description: 'Review a proposed AI use through the lens of examiner questions and documentation expectations.',
    useCase: 'Use before presenting an AI workflow to leadership, compliance, or audit.',
    whenToUse: 'When the workflow could affect customers, employees, controls, or regulated operations.',
    whenNotToUse: 'Do not ask AI to invent laws, citations, examiner positions, or approval language.',
    inputs: [
      { label: 'Use case', helper: 'The AI workflow under review.' },
      { label: 'Controls', helper: 'Known controls or review steps.' },
      { label: 'Documentation', helper: 'Policies, logs, testing notes, or approvals available.' },
    ],
    promptTemplate: 'You are reviewing a banking AI use case from an examiner-readiness perspective. Use case: [USE CASE]. Existing controls: [CONTROLS]. Documentation available: [DOCUMENTATION]. Do not invent regulatory citations. Identify examiner questions, documentation gaps, control weaknesses, and suggested next steps.',
    outputStructure: ['Examiner questions', 'Documentation gaps', 'Control weaknesses', 'Next steps'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add audit trace requirements.', 'Add board oversight framing.', 'Add validation and monitoring steps.'],
    exampleRun: 'Review an AI-assisted credit memo draft workflow before pilot.',
  },
  {
    id: 'decision-log-builder',
    title: 'Decision Log Builder',
    category: 'Risk & Governance',
    difficulty: 'Intermediate',
    description: 'Create a lightweight decision log for AI-assisted work so human judgment remains visible.',
    useCase: 'Use when AI helps draft or analyze, but a banker makes the final decision.',
    whenToUse: 'For internal decisions, review packages, and documented work products.',
    whenNotToUse: 'Do not use to paper over missing approvals or unsupported conclusions.',
    inputs: [
      { label: 'Decision', helper: 'What was decided or recommended.' },
      { label: 'AI role', helper: 'How AI was used.' },
      { label: 'Human review', helper: 'What the human checked or changed.' },
    ],
    promptTemplate: 'You are a banking documentation analyst. Build a concise decision log for the AI-assisted work below. Decision or recommendation: [DECISION]. AI role: [AI ROLE]. Human review performed: [HUMAN REVIEW]. Return a table with date, decision, source inputs, AI contribution, human review, open issues, and owner.',
    outputStructure: ['Decision log table', 'Open issues', 'Owner and next review date'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add evidence links.', 'Add approval status.', 'Add control owner and retention period.'],
    exampleRun: 'Document how AI helped summarize vendor due diligence notes.',
  },
  {
    id: 'vendor-risk-snapshot',
    title: 'Vendor Risk Snapshot',
    category: 'Vendor',
    difficulty: 'Starter',
    description: 'Summarize a vendor relationship into service, data, risk, and review questions.',
    useCase: 'Use before a formal vendor review or intake meeting.',
    whenToUse: 'When a team needs a structured first-pass vendor risk view.',
    whenNotToUse: 'Do not use to approve, renew, or onboard a vendor.',
    inputs: [
      { label: 'Vendor', helper: 'Name and service description.' },
      { label: 'Data access', helper: 'Types of data the vendor touches.' },
      { label: 'Criticality', helper: 'Operational impact if the service fails.' },
    ],
    promptTemplate: 'You are a banking vendor risk analyst. Create a vendor risk snapshot for: [VENDOR]. Service: [SERVICE]. Data access: [DATA ACCESS]. Criticality: [CRITICALITY]. Do not approve the vendor. Identify risk questions, missing documents, and likely review owners.',
    outputStructure: ['Vendor overview', 'Data sensitivity', 'Operational criticality', 'Key questions', 'Missing documents'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add SOC 2 review checklist.', 'Add business continuity questions.', 'Add subcontractor review questions.'],
    exampleRun: 'Create a snapshot for a marketing email platform that stores member contact data.',
  },
  {
    id: 'vendor-due-diligence',
    title: 'Vendor Due Diligence',
    category: 'Vendor',
    difficulty: 'Advanced',
    description: 'Structure a vendor due diligence review around documents, risks, gaps, and mitigations.',
    useCase: 'Use when reviewing vendor materials for a risk committee or owner.',
    whenToUse: 'When documentation is available and needs structured review.',
    whenNotToUse: 'Do not upload confidential contracts or nonpublic vendor findings into public tools.',
    inputs: [
      { label: 'Vendor package summary', helper: 'Documents reviewed without confidential detail.' },
      { label: 'Service criticality', helper: 'Low, moderate, high, or mission critical.' },
      { label: 'Known issues', helper: 'Exceptions, missing items, or concerns.' },
    ],
    promptTemplate: 'You are a banking third-party risk reviewer. Review the summarized vendor package below. Package summary: [SUMMARY]. Service criticality: [CRITICALITY]. Known issues: [ISSUES]. Identify due diligence gaps, risk implications, mitigations, and follow-up questions. Do not approve or reject the vendor.',
    outputStructure: ['Due diligence summary', 'Gap table', 'Risk implications', 'Mitigations', 'Follow-up questions'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add residual risk rating.', 'Add evidence owner.', 'Add renewal timeline and monitoring cadence.'],
    exampleRun: 'Review a core processor renewal package for missing cyber documentation.',
  },
  {
    id: 'data-sensitivity-classifier',
    title: 'Data Sensitivity Classifier',
    category: 'Data & Communication',
    difficulty: 'Starter',
    description: 'Classify work examples by data sensitivity before using AI.',
    useCase: 'Use to train bankers to decide what can and cannot go into public AI tools.',
    whenToUse: 'Before drafting, summarizing, or analyzing any source material with AI.',
    whenNotToUse: 'Do not use to downgrade data that policy classifies as restricted or confidential.',
    inputs: [
      { label: 'Work example', helper: 'What the user wants to enter into AI.' },
      { label: 'Data fields', helper: 'Any names, account data, numbers, internal information.' },
      { label: 'Tool type', helper: 'Public AI, approved enterprise AI, or internal system.' },
    ],
    promptTemplate: 'You are a banking data classification coach. Classify this work example for AI use. Work example: [EXAMPLE]. Data fields involved: [DATA FIELDS]. Tool type: [TOOL TYPE]. Return classification, what must be removed, whether public AI is appropriate, and safer alternatives.',
    outputStructure: ['Classification', 'Remove before use', 'Public AI suitability', 'Safer alternative', 'Reviewer note'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add red/yellow/green data tiers.', 'Add example transformations.', 'Add escalation guidance.'],
    exampleRun: 'Classify a request to summarize a member complaint email.',
  },
  {
    id: 'customer-communication-simplifier',
    title: 'Customer Communication Simplifier',
    category: 'Data & Communication',
    difficulty: 'Intermediate',
    description: 'Simplify complex banking language into clearer customer-facing language for review.',
    useCase: 'Use for plain-language rewrites of non-confidential customer communication drafts.',
    whenToUse: 'When the message is already approved in substance but needs clarity.',
    whenNotToUse: 'Do not use for promises, fee waivers, adverse action, or legal notices without review.',
    inputs: [
      { label: 'Draft message', helper: 'The non-confidential draft.' },
      { label: 'Audience', helper: 'Customer, member, small business, borrower, staff.' },
      { label: 'Required points', helper: 'Facts that must remain unchanged.' },
    ],
    promptTemplate: 'You are a banking communication editor. Simplify the draft below for [AUDIENCE]. Draft: [DRAFT]. Required points: [REQUIRED POINTS]. Constraints: preserve meaning, do not add promises, do not create legal or compliance claims, and flag any statement that needs review.',
    outputStructure: ['Simplified draft', 'Changes made', 'Review flags', 'Optional shorter version'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add readability target.', 'Add disclosure-preservation check.', 'Add tone alternatives.'],
    exampleRun: 'Simplify an overdraft alert explanation for a member service team.',
  },
  {
    id: 'procedure-simplifier',
    title: 'Procedure Simplifier',
    category: 'Operations',
    difficulty: 'Starter',
    description: 'Turn dense procedure language into a staff-ready checklist.',
    useCase: 'Use for internal training, job aids, and procedure refreshers.',
    whenToUse: 'When the source procedure is approved and non-confidential.',
    whenNotToUse: 'Do not use to change policy meaning or omit required controls.',
    inputs: [
      { label: 'Procedure text', helper: 'Approved procedure content.' },
      { label: 'User role', helper: 'The staff role performing the work.' },
      { label: 'Task moment', helper: 'When the checklist is used.' },
    ],
    promptTemplate: 'You are a banking operations trainer. Convert the approved procedure below into a role-specific checklist. Procedure: [PROCEDURE]. User role: [ROLE]. Task moment: [MOMENT]. Preserve required controls and flag any unclear or missing step. Output as a checklist with review notes.',
    outputStructure: ['Checklist', 'Required controls', 'Unclear steps', 'Supervisor review notes'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add control mapping.', 'Add training quiz questions.', 'Add exception-handling branch.'],
    exampleRun: 'Convert a debit card dispute procedure into a branch checklist.',
  },
  {
    id: 'meeting-notes-action-plan',
    title: 'Meeting Notes -> Action Plan',
    category: 'Operations',
    difficulty: 'Starter',
    description: 'Turn meeting notes into decisions, action items, owners, and follow-ups.',
    useCase: 'Use after internal meetings with non-confidential notes.',
    whenToUse: 'When notes are messy but decisions and owners need structure.',
    whenNotToUse: 'Do not include confidential personnel, customer, or board-sensitive content in public tools.',
    inputs: [
      { label: 'Notes', helper: 'Meeting notes without sensitive data.' },
      { label: 'Meeting purpose', helper: 'Why the group met.' },
      { label: 'Attendee roles', helper: 'Roles, not personal details if unnecessary.' },
    ],
    promptTemplate: 'You are a banking operations coordinator. Turn the meeting notes below into an action plan. Meeting purpose: [PURPOSE]. Attendee roles: [ROLES]. Notes: [NOTES]. Identify decisions, action items, owners by role, deadlines if stated, open questions, and risks.',
    outputStructure: ['Decision summary', 'Action plan table', 'Open questions', 'Risks and dependencies'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add RACI mapping.', 'Add follow-up email draft.', 'Add unresolved decision log.'],
    exampleRun: 'Create an action plan from notes about a branch procedure rollout.',
  },
  {
    id: 'ai-roi-framer',
    title: 'AI ROI Framer',
    category: 'Strategy',
    difficulty: 'Intermediate',
    description: 'Frame the expected value, cost, risk, and effort of an AI use case.',
    useCase: 'Use when leadership asks whether an AI workflow is worth pursuing.',
    whenToUse: 'Early in prioritization, before pilot design.',
    whenNotToUse: 'Do not invent savings, adoption rates, or vendor pricing.',
    inputs: [
      { label: 'Use case', helper: 'The workflow under consideration.' },
      { label: 'Current process', helper: 'Time, volume, pain points, and owners.' },
      { label: 'Known constraints', helper: 'Risk, data, vendor, or change limits.' },
    ],
    promptTemplate: 'You are a banking strategy analyst. Frame the ROI case for this AI use case without inventing numbers. Use case: [USE CASE]. Current process: [CURRENT PROCESS]. Known constraints: [CONSTRAINTS]. Return value drivers, cost drivers, risk factors, assumptions to validate, and pilot metrics.',
    outputStructure: ['Value drivers', 'Cost drivers', 'Risk factors', 'Assumptions', 'Pilot metrics'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add low/medium/high scenario ranges.', 'Add benefit owner.', 'Add measurement plan.'],
    exampleRun: 'Frame ROI for AI-assisted policy summarization in compliance.',
  },
  {
    id: 'ai-use-case-prioritizer',
    title: 'AI Use Case Prioritizer',
    category: 'Strategy',
    difficulty: 'Intermediate',
    description: 'Rank AI ideas by value, feasibility, risk, and readiness.',
    useCase: 'Use for workshop outputs, leadership discussions, or team planning.',
    whenToUse: 'When a team has too many ideas and needs an ordered pilot list.',
    whenNotToUse: 'Do not use as final governance approval.',
    inputs: [
      { label: 'Use cases', helper: 'List of candidate ideas.' },
      { label: 'Scoring criteria', helper: 'Value, risk, feasibility, readiness.' },
      { label: 'Constraints', helper: 'Budget, systems, staffing, or policy limits.' },
    ],
    promptTemplate: 'You are facilitating AI use case prioritization for a financial institution. Candidate use cases: [USE CASES]. Scoring criteria: [CRITERIA]. Constraints: [CONSTRAINTS]. Score each use case qualitatively for value, feasibility, risk, and readiness. Recommend a pilot order and explain tradeoffs.',
    outputStructure: ['Prioritization table', 'Top pilot candidates', 'Do-not-start-yet items', 'Key tradeoffs'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add weighted scoring.', 'Add control readiness column.', 'Add pilot charter outline.'],
    exampleRun: 'Prioritize five ideas from an operations leadership workshop.',
  },
  {
    id: 'executive-summary-builder',
    title: 'Executive Summary Builder',
    category: 'Executive',
    difficulty: 'Starter',
    description: 'Turn raw internal notes into a concise executive summary with decisions and risks.',
    useCase: 'Use for internal leadership updates from non-confidential source notes.',
    whenToUse: 'When executives need the point, implication, and next decision quickly.',
    whenNotToUse: 'Do not include market-sensitive, personnel, customer, or board-confidential data in public tools.',
    inputs: [
      { label: 'Source notes', helper: 'The facts to summarize.' },
      { label: 'Audience', helper: 'CEO, ELT, board committee, department head.' },
      { label: 'Decision needed', helper: 'What action the reader may need to take.' },
    ],
    promptTemplate: 'You are an executive communications analyst for a financial institution. Create a concise executive summary from the source notes. Audience: [AUDIENCE]. Decision needed: [DECISION]. Source notes: [NOTES]. Separate facts, implications, risks, and recommended next steps. Do not add facts not provided.',
    outputStructure: ['Executive summary', 'Implications', 'Risks', 'Decision or next step'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add board-level version.', 'Add one-page memo format.', 'Add confidence and source trace.'],
    exampleRun: 'Summarize AI pilot findings for an executive team update.',
  },
  {
    id: 'board-memo-assistant',
    title: 'Board Memo Assistant',
    category: 'Executive',
    difficulty: 'Advanced',
    description: 'Structure a board memo draft with background, decision, risk, and management recommendation.',
    useCase: 'Use to organize non-confidential management notes into board-ready structure.',
    whenToUse: 'When the memo needs disciplined structure before executive review.',
    whenNotToUse: 'Do not use public AI for confidential board materials or MNPI.',
    inputs: [
      { label: 'Topic', helper: 'The board item.' },
      { label: 'Background facts', helper: 'Approved facts to include.' },
      { label: 'Decision requested', helper: 'Approve, discuss, note, or direct.' },
    ],
    promptTemplate: 'You are a board memo drafting assistant for a financial institution. Topic: [TOPIC]. Background facts: [FACTS]. Decision requested: [DECISION]. Draft a structured memo with background, management recommendation, risk considerations, alternatives, and questions for board discussion. Do not add unsupported facts.',
    outputStructure: ['Memo title', 'Background', 'Recommendation', 'Risk considerations', 'Alternatives', 'Board questions'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add fiduciary framing.', 'Add risk appetite alignment.', 'Add appendix outline.'],
    exampleRun: 'Draft a board memo structure for approving an AI training program.',
  },
  {
    id: 'change-log-audit-narrative',
    title: 'Change Log -> Audit Narrative',
    category: 'Documentation',
    difficulty: 'Intermediate',
    description: 'Convert a change log into an audit-ready narrative of what changed, why, who reviewed it, and what evidence exists.',
    useCase: 'Use for policy, procedure, system, or control changes.',
    whenToUse: 'When a change needs clear documentation for internal audit or compliance review.',
    whenNotToUse: 'Do not use to fabricate approvals, dates, or evidence.',
    inputs: [
      { label: 'Change log', helper: 'List of changes with dates if available.' },
      { label: 'Reason for change', helper: 'Driver, issue, finding, or improvement.' },
      { label: 'Review evidence', helper: 'Known approvals or review steps.' },
    ],
    promptTemplate: 'You are a banking audit documentation analyst. Convert this change log into an audit narrative. Change log: [CHANGE LOG]. Reason for change: [REASON]. Review evidence: [EVIDENCE]. Do not invent approvals or dates. Identify missing evidence and open audit questions.',
    outputStructure: ['Audit narrative', 'Change table', 'Evidence available', 'Evidence missing', 'Open questions'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add control mapping.', 'Add retention checklist.', 'Add reviewer signoff fields.'],
    exampleRun: 'Turn procedure updates after a Reg E process change into an audit narrative.',
  },
  {
    id: 'policy-gap-spotter',
    title: 'Policy Gap Spotter',
    category: 'Documentation',
    difficulty: 'Advanced',
    description: 'Compare a proposed practice against an approved policy summary and flag gaps for review.',
    useCase: 'Use when teams need to prepare questions before compliance or policy owner review.',
    whenToUse: 'When both the proposed practice and policy summary can be shared without confidential data.',
    whenNotToUse: 'Do not use to issue legal interpretations or declare a practice compliant.',
    inputs: [
      { label: 'Policy summary', helper: 'Approved non-confidential policy requirements.' },
      { label: 'Proposed practice', helper: 'What the team wants to do.' },
      { label: 'Known constraints', helper: 'Timing, systems, staffing, or exceptions.' },
    ],
    promptTemplate: 'You are a banking policy review assistant. Compare the proposed practice against the approved policy summary. Policy summary: [POLICY SUMMARY]. Proposed practice: [PRACTICE]. Known constraints: [CONSTRAINTS]. Do not declare compliance. Identify alignment, gaps, questions for the policy owner, and documentation needed.',
    outputStructure: ['Alignment summary', 'Potential gaps', 'Policy owner questions', 'Documentation needed', 'Escalation note'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add control mapping.', 'Add exception log fields.', 'Add reviewer signoff checklist.'],
    exampleRun: 'Spot gaps between a proposed AI meeting-notes workflow and the acceptable use policy.',
  },
  {
    id: 'training-generator',
    title: 'Training Generator',
    category: 'Training',
    difficulty: 'Intermediate',
    description: 'Generate a short training module from approved source material.',
    useCase: 'Use for staff education, refreshers, and internal rollout materials.',
    whenToUse: 'When source material is approved and needs role-specific training structure.',
    whenNotToUse: 'Do not use for legal, HR, or compliance training without owner review.',
    inputs: [
      { label: 'Source material', helper: 'Approved policy, procedure, or guidance.' },
      { label: 'Audience role', helper: 'Who will receive the training.' },
      { label: 'Time available', helper: '5 minutes, 15 minutes, 30 minutes, etc.' },
    ],
    promptTemplate: 'You are a banking training designer. Create a short training module from approved source material. Audience role: [ROLE]. Time available: [TIME]. Source material: [SOURCE]. Include learning objective, key points, scenario, knowledge check, and manager review note. Do not change the source meaning.',
    outputStructure: ['Learning objective', 'Key points', 'Scenario', 'Knowledge check', 'Manager review note'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add quiz scoring.', 'Add facilitator guide.', 'Add job aid checklist.'],
    exampleRun: 'Create a 10-minute branch refresher on safe AI data handling.',
  },
  {
    id: 'incident-scenario-builder',
    title: 'Incident Scenario Builder',
    category: 'Training',
    difficulty: 'Advanced',
    description: 'Create realistic tabletop or discussion scenarios for AI, data, vendor, or operational incidents.',
    useCase: 'Use for training sessions, tabletop exercises, and readiness discussions.',
    whenToUse: 'When teams need practice recognizing and escalating risk.',
    whenNotToUse: 'Do not include real customer, employee, or security incident details in public tools.',
    inputs: [
      { label: 'Incident theme', helper: 'Data exposure, vendor outage, hallucinated output, complaint issue.' },
      { label: 'Audience', helper: 'Staff, managers, executives, compliance, IT.' },
      { label: 'Learning goal', helper: 'What behavior should improve.' },
    ],
    promptTemplate: 'You are a banking training scenario designer. Build a fictional incident scenario for training. Theme: [THEME]. Audience: [AUDIENCE]. Learning goal: [GOAL]. Use fabricated details only. Include scenario facts, injects, discussion questions, expected actions, and facilitator notes.',
    outputStructure: ['Scenario brief', 'Injects', 'Discussion questions', 'Expected actions', 'Facilitator notes'],
    reviewChecklist: STANDARD_REVIEW,
    expandContent: ['Add scoring rubric.', 'Add escalation map.', 'Add post-exercise action plan.'],
    exampleRun: 'Build a tabletop scenario for a public AI data-entry mistake.',
  },
];

export const PROMPT_CARD_CATEGORIES = Array.from(
  new Set(PROMPT_CARDS.map((card) => card.category)),
);
