// Catalog of record for the banker skills library: id, name, group.
// Approved in the "AiBI Banker Skills Catalog" doc on 2026-10-04. Change a
// name here and in the doc together; skills.test.ts checks every entry is
// built and matches.

import type { SkillGroup } from './types';

export const SKILL_CATALOG: readonly { readonly id: string; readonly name: string; readonly group: SkillGroup }[] = [
  { id: 'E1', name: 'Rewrite this email', group: 'everyday' },
  { id: 'E2', name: 'Reply to this email', group: 'everyday' },
  { id: 'E3', name: 'Write a status update', group: 'everyday' },
  { id: 'E4', name: 'Turn notes into a memo', group: 'everyday' },
  { id: 'E5', name: 'Announce a change to staff', group: 'everyday' },
  { id: 'E6', name: 'Audit this document', group: 'everyday' },
  { id: 'E7', name: 'Proofread this', group: 'everyday' },
  { id: 'E8', name: 'Check this against our policy', group: 'everyday' },
  { id: 'E9', name: 'Find what\'s missing', group: 'everyday' },
  { id: 'E10', name: 'Make this plain language', group: 'everyday' },
  { id: 'E11', name: 'Summarize this meeting', group: 'everyday' },
  { id: 'E12', name: 'Summarize this document', group: 'everyday' },
  { id: 'E13', name: 'Catch me up on this thread', group: 'everyday' },
  { id: 'E14', name: 'Compare these two versions', group: 'everyday' },
  { id: 'E15', name: 'Explain this to me', group: 'everyday' },
  { id: 'E16', name: 'Rebrand this document', group: 'everyday' },
  { id: 'E17', name: 'Plan my week', group: 'everyday' },
  { id: 'E18', name: 'Prep me for this meeting', group: 'everyday' },
  { id: 'E19', name: 'Build a checklist', group: 'everyday' },
  { id: 'E20', name: 'Draft a meeting request', group: 'everyday' },
  { id: 'X1', name: 'Clean up this spreadsheet', group: 'office' },
  { id: 'X2', name: 'Write a formula for this', group: 'office' },
  { id: 'X3', name: 'Turn this into a table', group: 'office' },
  { id: 'X4', name: 'Summarize this sheet', group: 'office' },
  { id: 'X5', name: 'Chart this data', group: 'office' },
  { id: 'X6', name: 'Reconcile these two lists', group: 'office' },
  { id: 'X7', name: 'Explain this workbook', group: 'office' },
  { id: 'X8', name: 'Start a tracker from our template', group: 'office' },
  { id: 'P1', name: 'Turn this into slides', group: 'office' },
  { id: 'P2', name: 'Rebrand this deck', group: 'office' },
  { id: 'P3', name: 'Build a deck from our template', group: 'office' },
  { id: 'P4', name: 'Turn this sheet into slides', group: 'office' },
  { id: 'P5', name: 'Tighten this deck', group: 'office' },
  { id: 'P6', name: 'Write speaker notes', group: 'office' },
  { id: 'MK1', name: 'Apply our brand voice', group: 'marketing' },
  { id: 'MK2', name: 'Write a brand style card', group: 'marketing' },
  { id: 'MK3', name: 'Write a campaign brief', group: 'marketing' },
  { id: 'MK4', name: 'Draft three ad variations', group: 'marketing' },
  { id: 'MK5', name: 'Write a rate promo', group: 'marketing' },
  { id: 'MK6', name: 'Check disclosures before review', group: 'marketing' },
  { id: 'MK7', name: 'Turn specs into member language', group: 'marketing' },
  { id: 'MK8', name: 'Write a product page', group: 'marketing' },
  { id: 'MK9', name: 'Plan a month of social posts', group: 'marketing' },
  { id: 'MK10', name: 'Write a member newsletter', group: 'marketing' },
  { id: 'MK11', name: 'Promote a community event', group: 'marketing' },
  { id: 'MK12', name: 'Write subject lines', group: 'marketing' },
  { id: 'MK13', name: 'Draft a creative brief', group: 'marketing' },
  { id: 'MK14', name: 'Name a product', group: 'marketing' },
  { id: 'MK15', name: 'Localize for a market', group: 'marketing' },
  { id: 'RT1', name: 'Reply to a member complaint', group: 'retail' },
  { id: 'RT2', name: 'Explain a hold or fee', group: 'retail' },
  { id: 'RT3', name: 'Coach a teller', group: 'retail' },
  { id: 'RT4', name: 'Prep a hard conversation', group: 'retail' },
  { id: 'RT5', name: 'Shrink a procedure to one page', group: 'retail' },
  { id: 'RT6', name: 'Write a branch huddle', group: 'retail' },
  { id: 'RT7', name: 'Write a needs-based conversation guide', group: 'retail' },
  { id: 'RT8', name: 'Fill a schedule gap', group: 'retail' },
  { id: 'RT9', name: 'Write a lobby sign', group: 'retail' },
  { id: 'RT10', name: 'Build the branch scorecard', group: 'retail' },
  { id: 'LN1', name: 'Draft an adverse-action letter', group: 'lending' },
  { id: 'LN2', name: 'Summarize a loan file', group: 'lending' },
  { id: 'LN3', name: 'List missing documents', group: 'lending' },
  { id: 'LN4', name: 'Write a credit memo section', group: 'lending' },
  { id: 'LN5', name: 'Write an exception memo', group: 'lending' },
  { id: 'LN6', name: 'Spread these financials', group: 'lending' },
  { id: 'LN7', name: 'Run a fair-lending pre-check', group: 'lending' },
  { id: 'LN8', name: 'Explain loan terms to a borrower', group: 'lending' },
  { id: 'LN9', name: 'Chase borrower documents', group: 'lending' },
  { id: 'LN10', name: 'Build the pipeline report', group: 'lending' },
  { id: 'LN11', name: 'Turn a credit memo into committee slides', group: 'lending' },
  { id: 'CO1', name: 'Summarize new guidance', group: 'compliance' },
  { id: 'CO2', name: 'Map a rule to our policy', group: 'compliance' },
  { id: 'CO3', name: 'Write a procedure', group: 'compliance' },
  { id: 'CO4', name: 'Review an ad for compliance', group: 'compliance' },
  { id: 'CO5', name: 'Screen an AI use case', group: 'compliance' },
  { id: 'CO6', name: 'Build a testing worksheet', group: 'compliance' },
  { id: 'CO7', name: 'Draft an exam response', group: 'compliance' },
  { id: 'CO8', name: 'Spot complaint trends', group: 'compliance' },
  { id: 'CO9', name: 'Build the board compliance deck', group: 'compliance' },
  { id: 'CO10', name: 'Build the compliance calendar', group: 'compliance' },
  { id: 'BA1', name: 'Scaffold a SAR narrative', group: 'bsa-aml' },
  { id: 'BA2', name: 'Check a narrative\'s five Ws', group: 'bsa-aml' },
  { id: 'BA3', name: 'Summarize an alert', group: 'bsa-aml' },
  { id: 'BA4', name: 'Draft a CDD baseline', group: 'bsa-aml' },
  { id: 'BA5', name: 'Write an EDD request', group: 'bsa-aml' },
  { id: 'BA6', name: 'Write a case closure note', group: 'bsa-aml' },
  { id: 'BA7', name: 'Explain a typology', group: 'bsa-aml' },
  { id: 'BA8', name: 'Build a training scenario', group: 'bsa-aml' },
  { id: 'BA9', name: 'Build the BSA board report', group: 'bsa-aml' },
  { id: 'OP1', name: 'Document a recurring task', group: 'operations' },
  { id: 'OP2', name: 'Map a workflow', group: 'operations' },
  { id: 'OP3', name: 'Explain a reconciliation break', group: 'operations' },
  { id: 'OP4', name: 'Summarize an exception report', group: 'operations' },
  { id: 'OP5', name: 'Write a vendor ticket', group: 'operations' },
  { id: 'OP6', name: 'Write a handoff note', group: 'operations' },
  { id: 'OP7', name: 'Write an incident summary', group: 'operations' },
  { id: 'OP8', name: 'Log time saved', group: 'operations' },
  { id: 'OP9', name: 'Build the daily ops dashboard', group: 'operations' },
  { id: 'EX1', name: 'Write a board memo', group: 'executive' },
  { id: 'EX2', name: 'Brief me before a meeting', group: 'executive' },
  { id: 'EX3', name: 'Pressure-test a vendor pitch', group: 'executive' },
  { id: 'EX4', name: 'Draft a strategy one-pager', group: 'executive' },
  { id: 'EX5', name: 'Compare us to peers', group: 'executive' },
  { id: 'EX6', name: 'Write a message from the CEO', group: 'executive' },
  { id: 'EX7', name: 'Set AI guardrails', group: 'executive' },
  { id: 'EX8', name: 'Build the board deck', group: 'executive' },
  { id: 'IS1', name: 'Render a tool verdict', group: 'infosec' },
  { id: 'IS2', name: 'Classify this data', group: 'infosec' },
  { id: 'IS3', name: 'Review a vendor questionnaire', group: 'infosec' },
  { id: 'IS4', name: 'Write a phishing alert', group: 'infosec' },
  { id: 'IS5', name: 'Prep an access review', group: 'infosec' },
  { id: 'IS6', name: 'Run a tabletop exercise', group: 'infosec' },
  { id: 'IS7', name: 'Track vendor risk', group: 'infosec' },
  { id: 'IS8', name: 'Write a security awareness tip', group: 'infosec' },
  { id: 'HR1', name: 'Build a training path', group: 'training-hr' },
  { id: 'HR2', name: 'Write a job description', group: 'training-hr' },
  { id: 'HR3', name: 'Draft interview questions', group: 'training-hr' },
  { id: 'HR4', name: 'Write a practice scenario', group: 'training-hr' },
  { id: 'HR5', name: 'Write a safe-use one-pager', group: 'training-hr' },
  { id: 'HR6', name: 'Draft a performance review', group: 'training-hr' },
  { id: 'HR7', name: 'Build an onboarding checklist', group: 'training-hr' },
  { id: 'HR8', name: 'Report training completion', group: 'training-hr' },
];
