import type { StructuredBuilderConfig } from './types';

export const _STRUCTURED_BUILDER_CONFIGS: Record<number, StructuredBuilderConfig> = {
  4: {
    moduleNumber: 4,
    testId: 'foundation-work-profile-builder',
    eyebrow: 'Build reusable context',
    title: 'Work Profile Scrubber',
    description: 'Keep useful role context and remove the details that should never become reusable prompt material.',
    scoreLabel: 'Profile',
    badLabel: 'Overexposed profile',
    badWay:
      'I manage Downtown branch complaints, including Maria Lopez account 872399. We are preparing a confidential Q3 staffing change. Write in my voice and mention our private member-retention plan.',
    previewLabel: 'Safe about-me.md preview',
    artifactHeading: 'Safe AI work profile',
    model: 'AiBI work profile scrubber',
    dataset: 'Work Profile Examples',
    reviewChecklist: ['No customer examples', 'No confidential bank plans', 'Tone guidance is concrete'],
    completeLine: 'The profile is useful without exposing customer, account, strategy, or confidential institution data.',
    incompleteLine: 'The profile should not be reusable until the sensitive context is removed and boundaries are explicit.',
    moves: [
      {
        id: 'role',
        label: 'Keep role context',
        short: 'Role and audience stay because they improve outputs.',
        missing: 'The model will not know the work context.',
        artifactLine: 'Role: community banking operator supporting branch, member-service, and manager-ready communication.',
      },
      {
        id: 'tone',
        label: 'Set tone',
        short: 'Tone guidance is concrete and reusable.',
        missing: 'The model may guess the voice.',
        artifactLine: 'Tone: concise, practical, plain-language, with action and owner visible early.',
      },
      {
        id: 'strip',
        label: 'Strip examples',
        short: 'Customer, account, and confidential examples are removed.',
        missing: 'The profile still contains sensitive examples.',
        artifactLine: 'Never include: customer names, account numbers, private complaints, confidential staffing, or strategy details.',
      },
      {
        id: 'boundary',
        label: 'Add boundary',
        short: 'The profile says when to stop and verify.',
        missing: 'The next user may treat draft output as final.',
        artifactLine: 'Boundary: produce drafts only; a human verifies policy, numbers, and any customer-impacting language.',
      },
    ],
  },
  5: {
    moduleNumber: 5,
    testId: 'foundation-project-brief-builder',
    eyebrow: 'Build scoped context',
    title: 'Project Brief Builder',
    description: 'Turn a vague rollout request into bounded context AI can reuse without drifting.',
    scoreLabel: 'Brief',
    badLabel: 'Vague request',
    badWay:
      'Help with the AI rollout. Make it good for everyone, include anything important, and draft what leadership needs.',
    previewLabel: 'Reusable brief preview',
    artifactHeading: 'Project Brief Template',
    model: 'AiBI project brief builder',
    dataset: 'Project Brief Scenario',
    reviewChecklist: ['Project data is sanitized', 'Out-of-scope work is explicit', 'Reviewer is named'],
    completeLine: 'The brief is scoped enough for another teammate to reuse and review.',
    incompleteLine: 'The brief needs audience, source, constraints, success metric, and reviewer before reuse.',
    moves: [
      {
        id: 'goal',
        label: 'Define goal',
        short: 'The work has one outcome.',
        missing: 'The model will expand the project on its own.',
        artifactLine: 'Goal: produce a manager-ready rollout brief for one approved internal AI use case.',
      },
      {
        id: 'audience',
        label: 'Name audience',
        short: 'The reader and decision level are clear.',
        missing: 'The output may aim at the wrong reader.',
        artifactLine: 'Audience: department manager and compliance reviewer, not customers or public distribution.',
      },
      {
        id: 'source',
        label: 'Bound source',
        short: 'The model only uses sanitized source material.',
        missing: 'The model may invent context or pull from unsafe material.',
        artifactLine: 'Source: sanitized process notes and approved policy excerpts only.',
      },
      {
        id: 'constraint',
        label: 'Set constraints',
        short: 'Out-of-scope work and review owner are named.',
        missing: 'Scope creep and review gaps stay hidden.',
        artifactLine: 'Constraints: no customer data, no legal conclusions, no launch approval; reviewer: named manager.',
      },
      {
        id: 'metric',
        label: 'Add success metric',
        short: 'The brief says what good looks like.',
        missing: 'The team cannot judge whether the draft helped.',
        artifactLine: 'Success metric: reviewer can identify action, owner, risk, and next step in under two minutes.',
      },
    ],
  },
  6: {
    moduleNumber: 6,
    testId: 'foundation-document-workflow-builder',
    eyebrow: 'Build source discipline',
    title: 'Document Workflow Builder',
    description: 'Repair a weak file prompt so unsupported answers are surfaced instead of invented.',
    scoreLabel: 'Source',
    badLabel: 'Weak file prompt',
    badWay:
      'Read this policy PDF and summarize the important stuff. Fill in anything missing from your general knowledge and make it sound complete.',
    previewLabel: 'Source-grounded workflow preview',
    artifactHeading: 'Document Workflow Prompt',
    model: 'AiBI document workflow builder',
    dataset: 'Source-Grounded Workflow',
    reviewChecklist: ['Source-only instruction is present', 'Citations or references are required', 'Reviewer checks claims against source'],
    completeLine: 'The workflow forces source-only answers, visible gaps, and human verification.',
    incompleteLine: 'The workflow is still vulnerable to unsupported claims until every source control is present.',
    moves: [
      {
        id: 'source-only',
        label: 'Source only',
        short: 'The model cannot answer from general knowledge.',
        missing: 'The model may fill gaps from memory.',
        artifactLine: 'Use only the provided document. Do not use general knowledge to fill missing information.',
      },
      {
        id: 'narrow',
        label: 'Ask narrowly',
        short: 'The question is bounded to the task.',
        missing: 'The output may become a broad essay.',
        artifactLine: 'Extract only owner, deadline, required action, exception, and evidence source.',
      },
      {
        id: 'cite',
        label: 'Require reference',
        short: 'Each claim points back to the source.',
        missing: 'The reviewer cannot trace claims.',
        artifactLine: 'For every claim, include section/page reference or quote label from the source.',
      },
      {
        id: 'gap',
        label: 'Name gaps',
        short: 'Missing answers become review flags.',
        missing: 'Unsupported gaps can look complete.',
        artifactLine: 'If the answer is not in the source, write "not found in source" and flag for review.',
      },
      {
        id: 'review',
        label: 'Add verification',
        short: 'A person checks the final summary.',
        missing: 'The model output may bypass human review.',
        artifactLine: 'Reviewer checks all dates, thresholds, and policy claims before circulation.',
      },
    ],
  },
  8: {
    moduleNumber: 8,
    testId: 'foundation-workflow-map-builder',
    eyebrow: 'Build the control path',
    title: 'Workflow Control Map',
    description: 'Place human checkpoints before customer-impacting or money-moving steps.',
    scoreLabel: 'Controls',
    badLabel: 'Unsafe automation flow',
    badWay:
      'Customer complaint arrives -> AI drafts response -> AI sends response -> monthly QA samples a few cases.',
    previewLabel: 'Controlled workflow preview',
    artifactHeading: 'Workflow Map',
    model: 'AiBI workflow control mapper',
    dataset: 'Workflow Map Scenario',
    reviewChecklist: ['AI never owns the decision', 'Handoffs are named', 'Blocked actions are explicit'],
    completeLine: 'The workflow shows the happy path, failure path, human owner, and retained evidence.',
    incompleteLine: 'The workflow is not deployable until decision, send, and failure controls are visible.',
    moves: [
      {
        id: 'trigger',
        label: 'Name trigger',
        short: 'The workflow starts from a specific event.',
        missing: 'The process begins too vaguely to control.',
        artifactLine: 'Trigger: sanitized customer complaint or internal request enters the approved intake queue.',
      },
      {
        id: 'assist',
        label: 'Limit AI assist',
        short: 'AI drafts and organizes; it does not decide.',
        missing: 'AI may appear to own judgment.',
        artifactLine: 'AI assist: summarize facts, draft internal notes, and list missing evidence only.',
      },
      {
        id: 'checkpoint',
        label: 'Add checkpoint',
        short: 'A named human reviews before impact.',
        missing: 'Customer-facing work can leave without accountability.',
        artifactLine: 'Human checkpoint: named reviewer approves, edits, or rejects before any customer-facing action.',
      },
      {
        id: 'escalation',
        label: 'Add escalation',
        short: 'Red-zone issues route out of the flow.',
        missing: 'Exceptions can be handled by the wrong person.',
        artifactLine: 'Escalation: fees, disputes, credit, legal, compliance, or NPI issues move to approved process.',
      },
      {
        id: 'archive',
        label: 'Retain evidence',
        short: 'The workflow keeps a review trail.',
        missing: 'The team cannot audit what happened.',
        artifactLine: 'Archive: retain prompt, source, draft, edits, reviewer, decision, and final artifact.',
      },
    ],
  },
  10: {
    moduleNumber: 10,
    testId: 'foundation-role-use-case-builder',
    eyebrow: 'Build the role pilot',
    title: 'Role Use-Case Builder',
    description: 'Narrow a broad AI idea into one use case a manager can review, pilot, and govern.',
    scoreLabel: 'Use case',
    badLabel: 'Too broad to pilot',
    badWay:
      'Use AI to improve lending productivity across the department and make staff faster.',
    previewLabel: 'Role use-case card preview',
    artifactHeading: 'Role Use-Case Card',
    model: 'AiBI role use-case builder',
    dataset: 'Role Use-Case Scenarios',
    reviewChecklist: ['Input shape is sanitized', 'Reviewer checks the right failure mode', 'Escalation is clear'],
    completeLine: 'The use case is narrow, reviewable, and safe enough for a manager pilot discussion.',
    incompleteLine: 'The use case is not ready until input, AI work, reviewer, failure mode, and escalation are visible.',
    moves: [
      {
        id: 'role',
        label: 'Pick role',
        short: 'The use case names a department and daily task.',
        missing: 'A generic use case cannot be reviewed by a manager.',
        artifactLine: 'Role/task: lending staff prepare sanitized borrower-meeting notes from approved templates.',
      },
      {
        id: 'input',
        label: 'Shape input',
        short: 'Input is sanitized and repeatable.',
        missing: 'The team may paste raw files or customer data.',
        artifactLine: 'Input: redacted meeting purpose, approved product notes, and placeholder borrower facts only.',
      },
      {
        id: 'ai-task',
        label: 'Limit AI task',
        short: 'AI drafts support material, not a decision.',
        missing: 'The AI task may drift into regulated judgment.',
        artifactLine: 'AI task: draft prep notes, questions to ask, and missing-information checklist.',
      },
      {
        id: 'reviewer',
        label: 'Name reviewer',
        short: 'A human owner checks the right thing.',
        missing: 'No one owns fact, tone, or policy review.',
        artifactLine: 'Reviewer: lender verifies facts, policy fit, and customer-facing language before use.',
      },
      {
        id: 'failure',
        label: 'Define failure',
        short: 'The card says what can go wrong.',
        missing: 'The pilot cannot measure risk.',
        artifactLine: 'Failure mode: invented borrower facts, unsupported policy claims, or implied credit recommendation.',
      },
      {
        id: 'escalate',
        label: 'Set escalation',
        short: 'Red-zone work routes out of the use case.',
        missing: 'Sensitive exceptions may stay in the pilot flow.',
        artifactLine: 'Escalate: credit decision, adverse action, NPI, or exception approval moves to approved process.',
      },
    ],
  },
  11: {
    moduleNumber: 11,
    testId: 'foundation-prompt-library-builder',
    eyebrow: 'Build reusable assets',
    title: 'Prompt Library Builder',
    description: 'Upgrade a one-off prompt into a managed library item with version, safety note, and example.',
    scoreLabel: 'Library',
    badLabel: 'One-off prompt',
    badWay:
      'Prompt: make this better. Saved in personal notes with no example, safety note, owner, or review date.',
    previewLabel: 'Managed prompt card preview',
    artifactHeading: 'Personal Prompt Library',
    model: 'AiBI prompt library builder',
    dataset: 'Prompt Library Samples',
    reviewChecklist: ['Each prompt has a safety note', 'Examples are sanitized', 'Stale prompts have a review cadence'],
    completeLine: 'The prompt card is reusable, inspectable, versioned, and safe to share with a colleague.',
    incompleteLine: 'The prompt is still a one-off until it has purpose, prompt text, safety note, example, and review cadence.',
    moves: [
      {
        id: 'name',
        label: 'Name asset',
        short: 'The library item has a clear use case.',
        missing: 'A colleague cannot tell when to use it.',
        artifactLine: 'Name/use case: staff email rewrite for internal action requests.',
      },
      {
        id: 'prompt',
        label: 'Write prompt',
        short: 'The prompt includes placeholders and output shape.',
        missing: 'The user still has to invent the prompt each time.',
        artifactLine: 'Prompt: rewrite redacted notes into action, owner, deadline, and human-review note.',
      },
      {
        id: 'safety',
        label: 'Add safety note',
        short: 'The card says what not to paste.',
        missing: 'Sensitive data could enter a repeat workflow.',
        artifactLine: 'Safety note: use placeholders only; do not paste customer names, account data, NPI, or confidential plans.',
      },
      {
        id: 'example',
        label: 'Add example',
        short: 'A sanitized before/after makes reuse easier.',
        missing: 'The prompt is hard to inspect or teach.',
        artifactLine: 'Example: [MEMBER] asks about [ACCOUNT REMOVED]; output keeps action and verification note.',
      },
      {
        id: 'version',
        label: 'Version it',
        short: 'The card has a version and review cadence.',
        missing: 'The team cannot tell whether the prompt is stale.',
        artifactLine: 'Version: v1.0; review monthly or when policy, process, or model behavior changes.',
      },
    ],
  },
  12: {
    moduleNumber: 12,
    testId: 'foundation-final-package-builder',
    eyebrow: 'Build the credential evidence',
    title: 'Final Package Builder',
    description: 'Assemble the evidence chain that proves AI-assisted work stayed human-owned.',
    scoreLabel: 'Package',
    badLabel: 'Thin final submission',
    badWay:
      'Submit the polished answer and say AI helped. No raw output, no source, no edits, and no safety boundary.',
    previewLabel: 'Foundation packet preview',
    artifactHeading: 'Foundation Packet Summary',
    model: 'AiBI final package builder',
    dataset: 'Foundation Packet Materials',
    reviewChecklist: ['Raw output is preserved', 'Human edits are annotated', 'Safe AI pledge is specific'],
    completeLine: 'The package lets a reviewer trace input, model work, human edits, verification, and safety judgment.',
    incompleteLine: 'The package is not credential-ready until the evidence chain and human ownership are visible.',
    moves: [
      {
        id: 'workflow',
        label: 'Name workflow',
        short: 'The submission starts with one bounded workflow.',
        missing: 'A reviewer cannot tell what work was performed.',
        artifactLine: 'Workflow: one repeatable banking task with audience, source, and success criteria named.',
      },
      {
        id: 'input',
        label: 'Show input',
        short: 'Sanitized input and prompt are preserved.',
        missing: 'The reviewer cannot inspect what the model received.',
        artifactLine: 'Input evidence: sanitized source, prompt, placeholders, and what-not-to-paste boundary.',
      },
      {
        id: 'raw',
        label: 'Keep raw output',
        short: 'The unedited AI output is visible.',
        missing: 'Human judgment cannot be distinguished from model output.',
        artifactLine: 'Raw output: preserved exactly enough for review, with sensitive data excluded.',
      },
      {
        id: 'edits',
        label: 'Annotate edits',
        short: 'Human changes are explained.',
        missing: 'The package does not prove ownership.',
        artifactLine: 'Human edits: facts checked, unsupported claims removed, tone adjusted, final artifact approved.',
      },
      {
        id: 'safety',
        label: 'State boundary',
        short: 'The package names the safety decision.',
        missing: 'The reviewer cannot see why the use was allowed.',
        artifactLine: 'Safety boundary: data zone, approved tool path, reviewer, escalation trigger, and retention note.',
      },
      {
        id: 'pledge',
        label: 'Add pledge',
        short: 'The learner commits to reuse rules.',
        missing: 'The packet lacks a forward-looking behavior commitment.',
        artifactLine: 'Pledge: I will verify facts, protect customer data, retain review evidence, and escalate red-zone work.',
      },
    ],
  },
};
