// AiBI-Foundation Module 4: Your AI Work Profile
// Pillar: Understanding | Estimated: 30 minutes
// Key Output: AI Work Profile
// roleSpecific: true — role-specific spotlights vary by department

import type { Module } from './types';

export const module4: Module = {
  number: 4,
  id: 'm4-ai-work-profile',
  title: 'Your AI Work Profile',
  pillar: 'understanding',
  estimatedMinutes: 30,
  keyOutput: 'AI Work Profile',
  roleSpecific: true,
  tables: [
    {
      id: 'm4-feature-matrix',
      caption: 'Platform Feature Matrix — Eight Features Across Primary Banking AI Platforms',
      columns: [
        { header: 'Feature', key: 'feature' },
        { header: 'ChatGPT', key: 'chatgpt' },
        { header: 'Claude', key: 'claude' },
        { header: 'Perplexity', key: 'perplexity' },
        { header: 'M365 Copilot', key: 'copilot' },
        { header: 'NotebookLM', key: 'notebooklm' },
        { header: 'Best Banking Use', key: 'bankingUse' },
      ],
      rows: [
        {
          feature: 'Deep Research / Web Search',
          chatgpt: 'Deep Research mode (Plus)',
          claude: 'Limited (no live web access by default)',
          perplexity: 'Native — all searches are web-grounded with citations',
          copilot: 'Bing-grounded search in some contexts',
          notebooklm: 'No web search — queries limited to uploaded source documents',
          bankingUse: 'Regulatory research, market intelligence, competitive analysis',
        },
        {
          feature: 'File Analysis',
          chatgpt: 'Upload PDFs, Excel, Word, images (Plus)',
          claude: 'Upload PDFs and documents (Pro)',
          perplexity: 'Limited file analysis',
          copilot: 'Native SharePoint and OneDrive document access',
          notebooklm: 'Core capability — upload up to 50 sources; semantic querying across all documents',
          bankingUse: 'Loan document QC, policy analysis, financial statement review',
        },
        {
          feature: 'Voice Mode',
          chatgpt: 'Advanced Voice Mode (Plus)',
          claude: 'Not available',
          perplexity: 'Not available',
          copilot: 'Teams integration (transcription and summary)',
          notebooklm: 'Audio Overview — generates a two-host podcast discussion of uploaded documents',
          bankingUse: 'Hands-free drafting, meeting transcription, on-the-go research',
        },
        {
          feature: 'Custom Instructions / System Prompt',
          chatgpt: 'Custom Instructions + Projects (Plus)',
          claude: 'Custom system prompts in Projects (Pro)',
          perplexity: 'Spaces with custom instructions (Pro)',
          copilot: 'Not configurable at staff level',
          notebooklm: 'Notebook instructions allow custom focus and response style per notebook',
          bankingUse: 'Persistent role context, brand voice, compliance constraints across sessions',
        },
        {
          feature: 'Image Generation',
          chatgpt: 'DALL-E 3 integrated (Plus)',
          claude: 'Not available',
          perplexity: 'Not available',
          copilot: 'Image generation via Designer integration',
          notebooklm: 'Not available',
          bankingUse: 'Marketing mockups, presentation graphics, training materials',
        },
        {
          feature: 'Workspace Integration',
          chatgpt: 'GPT connectors (beta)',
          claude: 'Limited integrations',
          perplexity: 'Limited integrations',
          copilot: 'Native Outlook, Teams, Word, Excel, PowerPoint, SharePoint',
          notebooklm: 'Google Workspace (Drive source sync in NotebookLM Plus)',
          bankingUse: 'Email drafting, meeting summaries, document creation in familiar tools',
        },
        {
          feature: 'Long Context / Document Length',
          chatgpt: '128K tokens (Plus)',
          claude: '200K tokens — industry-leading long context (Pro)',
          perplexity: 'Standard context',
          copilot: 'Context limited to specific document',
          notebooklm: 'Up to 50 sources per notebook — optimized for document corpus querying',
          bankingUse: 'Processing lengthy regulatory documents, multi-file analysis',
        },
        {
          feature: 'Code / Data Analysis',
          chatgpt: 'Code Interpreter / Advanced Data Analysis (Plus)',
          claude: 'Strong code analysis (Pro)',
          perplexity: 'Limited',
          copilot: 'Excel Copilot for spreadsheet analysis',
          notebooklm: 'Not available — document-focused tool only',
          bankingUse: 'Analyzing loan data spreadsheets, creating charts, automating Excel tasks',
        },
      ],
    },
    {
      id: 'm4-role-spotlights',
      caption: 'Role-Specific Feature Spotlight — Recommended Feature Clusters by Department',
      columns: [
        { header: 'Role', key: 'role' },
        { header: 'Primary Features', key: 'features' },
        { header: 'Platform Recommendation', key: 'platform' },
        { header: 'Example Use Case', key: 'example' },
      ],
      rows: [
        {
          role: 'Lending',
          features: 'File Analysis, Deep Research, Custom Instructions',
          platform: 'ChatGPT Plus (file analysis) + Perplexity (market research)',
          example: 'Upload a loan package to ChatGPT, ask it to flag missing documentation and summarize risk factors. Use Perplexity to research the borrower\'s sector with cited sources.',
        },
        {
          role: 'Compliance',
          features: 'Web Search with Citations, Document Semantic Search, Long Context',
          platform: 'Perplexity (research) + NotebookLM (policy querying) + Claude (long docs)',
          example: 'Upload your institution\'s BSA policy to NotebookLM, then query it against a specific transaction scenario. Use Perplexity to cross-reference with current FinCEN guidance.',
        },
        {
          role: 'Operations',
          features: 'Meeting Summaries, File Analysis, Custom Instructions',
          platform: 'Microsoft 365 Copilot (if licensed) or ChatGPT Plus',
          example: 'Use Copilot in Teams to auto-generate meeting minutes. Use ChatGPT to analyze exception report exports and identify top recurring issues.',
        },
        {
          role: 'Marketing',
          features: 'Image Generation, Custom Instructions, Long-Form Writing',
          platform: 'ChatGPT Plus (image + writing) + Claude (brand voice)',
          example: 'Create a Custom Instruction in ChatGPT with your institution\'s brand voice guide. Generate campaign copy, then create mockup images with DALL-E 3 for stakeholder review.',
        },
        {
          role: 'Retail / Frontline',
          features: 'Quick Drafting, Email Assistance, Knowledge Base Q&A',
          platform: 'Microsoft 365 Copilot (if licensed) or Gemini (Google Workspace)',
          example: 'Use Copilot in Outlook to draft member responses to complex account inquiries. Use NotebookLM with your product knowledge base to quickly answer staff questions.',
        },
        {
          role: 'Finance / Accounting',
          features: 'Excel Analysis, Data Interpretation, Report Drafting',
          platform: 'Microsoft 365 Copilot (Excel Copilot) or ChatGPT Plus (Code Interpreter)',
          example: 'Use Excel Copilot to analyze monthly variance reports and generate a plain-language summary. Use ChatGPT Code Interpreter to create visualizations from loan portfolio data.',
        },
      ],
    },
  ],
  activities: [
    {
      id: '4.1',
      title: 'Feature Discovery',
      description: 'Select one advanced feature from the feature matrix. Execute a work-related task using that feature and record the institutional impact. The task should be something you would normally do manually — research, document analysis, drafting, or data review.',
      type: 'free-text',
      fields: [
        {
          id: 'feature-selected',
          label: 'Which feature did you use? (e.g., File Analysis, Deep Research, Custom Instructions)',
          type: 'select',
          required: true,
          options: [
            { value: 'file-analysis', label: 'File Analysis — uploaded and analyzed a document' },
            { value: 'deep-research', label: 'Deep Research / Web Search — researched a topic with citations' },
            { value: 'custom-instructions', label: 'Custom Instructions — configured persistent role context' },
            { value: 'voice-mode', label: 'Voice Mode — used hands-free interaction' },
            { value: 'excel-analysis', label: 'Excel / Data Analysis — analyzed data or created visualizations' },
            { value: 'meeting-summary', label: 'Meeting Summary — summarized a meeting transcript or notes' },
            { value: 'image-generation', label: 'Image Generation — created a visual for work use' },
            { value: 'other', label: 'Other feature not listed above' },
          ],
        },
        {
          id: 'observation-log',
          label: 'Describe the outcome and the time saved or value created. What would you do differently next time?',
          type: 'textarea',
          minLength: 50,
          required: true,
          placeholder: 'Be specific: what was the task, what did the AI produce, how long did it take vs. doing it manually, and what was the quality of the output? Would you use this feature again for this type of task?',
        },
      ],
      completionTrigger: 'artifact-download',
      artifactId: 'platform-feature-reference-card',
    },
  ],
  artifacts: [
    {
      id: 'platform-feature-reference-card',
      title: 'Platform Feature Reference Card',
      description: 'One-page quick reference card matching your onboarding platform to its key features and top banking use cases. Front: feature matrix for your platform. Back: role-specific workflow shortcuts.',
      format: 'pdf',
      triggeredBy: '4.1',
      dynamic: false,
      downloadHref: '/downloads/platform-feature-reference-card.pdf',
    },
  ],
} as const;
