-- Plan F continuation — Migration 00022
-- Migrate the AiBI-P course prompts (content/courses/foundations/prompt-library.ts)
-- into toolbox_library_skills as published kind='template' rows with v1 content
-- snapshots in toolbox_library_skill_versions.
--
-- Source count at generation time: 22 prompts (modules 3, 4, 7, 8, 9).
--
-- Idempotent:
--   * skill insert uses ON CONFLICT (slug) DO NOTHING
--   * version insert uses ON CONFLICT (library_skill_id, version) DO NOTHING
--
-- Pillar defaults to 'C' (Capable) for all rows; content team can override
-- per-skill later. Category derives from each prompt's PromptRole via
-- ROLE_LABELS in the source data file.
--
-- Generated by scripts/gen-migration-22.mjs (not committed). NOT auto-applied;
-- the user applies via 'supabase db push' manually.

do $$
declare
  v_skill_id uuid;
begin

  -- Your First ChatGPT Banking Query (m3-first-chatgpt)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m3-first-chatgpt', 'template', 'Your First ChatGPT Banking Query', $p$A structured summary of the guidance with key dates, affected institutions, and required actions — written in plain language suitable for forwarding to your compliance committee.$p$, 'C', 'Compliance', 'beginner', 'aibi-p/module-3', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm3-first-chatgpt';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm3-first-chatgpt',
    'title', 'Your First ChatGPT Banking Query',
    'description', $p$A structured summary of the guidance with key dates, affected institutions, and required actions — written in plain language suitable for forwarding to your compliance committee.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a compliance analyst at a community bank under $1B in assets. Summarize the following regulatory development for a non-technical compliance committee audience:

Topic: The most recent interagency guidance on third-party risk management for AI and technology vendors.

For each key point, provide:
1. What changed or was clarified
2. Which institution functions are affected (lending, operations, IT, compliance)
3. The practical action required within the next 90 days

Constraints:
- Do not cite specific regulation numbers unless you can verify them. If unsure, write "[verify citation]" instead.
- Keep the summary under 400 words.
- Use plain language — no jargon that a board member could not understand.
- End with a one-sentence recommendation for next steps.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A structured summary of the guidance with key dates, affected institutions, and required actions — written in plain language suitable for forwarding to your compliance committee.$p$::text),
    'pillar', 'C',
    'category', 'Compliance',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'beginner',
    'course_source_ref', 'aibi-p/module-3'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Your First Copilot Email Draft (m3-first-copilot)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m3-first-copilot', 'template', 'Your First Copilot Email Draft', $p$A professional, empathetic email draft in your institution's voice that explains the rate change clearly and offers to discuss alternatives. Ready for review and sending.$p$, 'C', 'Retail / Frontline', 'beginner', 'aibi-p/module-3', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm3-first-copilot';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm3-first-copilot',
    'title', 'Your First Copilot Email Draft',
    'description', $p$A professional, empathetic email draft in your institution's voice that explains the rate change clearly and offers to discuss alternatives. Ready for review and sending.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$Draft an email to a business checking customer explaining that their promotional money market rate is expiring next month and transitioning to the standard rate.

Tone: Professional, empathetic, relationship-focused. This is a community bank — we know our customers by name.

Include:
1. A clear explanation of the rate change with specific dates (use [DATE] placeholders)
2. The new rate (use [RATE] placeholder) and how it compares to the promotional rate
3. Two alternative options the customer can explore (CD ladder, relationship pricing)
4. A direct phone number and name for follow-up (use [BANKER NAME] and [PHONE] placeholders)

Constraints:
- Do not make claims about rates being "competitive" or "best available" — let the customer decide.
- Do not use exclamation points or marketing language. This is a service communication, not a sales email.
- Keep under 200 words.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A professional, empathetic email draft in your institution's voice that explains the rate change clearly and offers to discuss alternatives. Ready for review and sending.$p$::text),
    'pillar', 'C',
    'category', 'Retail / Frontline',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'beginner',
    'course_source_ref', 'aibi-p/module-3'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Your First Claude Analysis (m3-first-claude)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m3-first-claude', 'template', 'Your First Claude Analysis', $p$A structured analysis with the top five key provisions, a plain-language summary of each, and flagged items requiring committee review — formatted as a table you can paste into a memo.$p$, 'C', 'Operations', 'beginner', 'aibi-p/module-3', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm3-first-claude';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm3-first-claude',
    'title', 'Your First Claude Analysis',
    'description', $p$A structured analysis with the top five key provisions, a plain-language summary of each, and flagged items requiring committee review — formatted as a table you can paste into a memo.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are an operations manager at a community bank reviewing an internal policy document. I will upload the document in the next message.

Your task:
1. Identify the five most important provisions that directly affect day-to-day staff operations
2. For each provision, provide: a plain-language summary (one sentence), the affected department(s), and whether it requires staff training or process changes
3. Flag any provisions that are ambiguous or could be interpreted multiple ways — these need committee discussion

Format: A Markdown table with columns:
| Provision | Summary | Affected Dept | Action Required | Ambiguity Flag |

Constraints:
- Do not rewrite the policy. Summarize and flag — do not recommend changes.
- If you are unsure whether a provision requires action, flag it as "[NEEDS REVIEW]" rather than guessing.
- Do not include provisions that are purely administrative (e.g., document revision dates, signature blocks).

After the table, provide a two-sentence executive summary suitable for opening a committee meeting.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A structured analysis with the top five key provisions, a plain-language summary of each, and flagged items requiring committee review — formatted as a table you can paste into a memo.$p$::text),
    'pillar', 'C',
    'category', 'Operations',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'beginner',
    'course_source_ref', 'aibi-p/module-3'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- CRE Lending Trends Deep Research (m4-lending-deep-research)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m4-lending-deep-research', 'template', 'CRE Lending Trends Deep Research', $p$A multi-page research report with cited sources covering vacancy rates, cap rate trends, delinquency data, and regulatory commentary — specific to your geographic market.$p$, 'C', 'Lending', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm4-lending-deep-research';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm4-lending-deep-research',
    'title', 'CRE Lending Trends Deep Research',
    'description', $p$A multi-page research report with cited sources covering vacancy rates, cap rate trends, delinquency data, and regulatory commentary — specific to your geographic market.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$Use Deep Research to analyze current commercial real estate (CRE) lending conditions in the [YOUR STATE/REGION] market.

I need a market intelligence brief I can present to my loan committee. Cover:

1. Current CRE vacancy rates by property type (office, retail, industrial, multifamily) with year-over-year trend
2. Cap rate movements over the past 12 months
3. CRE delinquency rates at community banks ($100M-$1B in assets) vs. large banks
4. Any recent regulatory commentary or guidance on CRE concentration risk
5. Two to three specific risks a community bank lender should monitor in the next 6 months

Requirements:
- Cite every data point with source name, publication, and date. If a source cannot be verified, exclude the data point.
- Distinguish between national data and regional/state-level data. My committee cares about local conditions.
- Use FDIC Call Report data or Federal Reserve data where available.
- Do not include projections or forecasts from unnamed "industry experts."
- Format as a structured brief with section headers, suitable for a 10-minute committee presentation.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A multi-page research report with cited sources covering vacancy rates, cap rate trends, delinquency data, and regulatory commentary — specific to your geographic market.$p$::text),
    'pillar', 'C',
    'category', 'Lending',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- CFPB Overdraft Guidance Research (m4-compliance-perplexity)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m4-compliance-perplexity', 'template', 'CFPB Overdraft Guidance Research', $p$A cited research summary with direct links to CFPB guidance documents, enforcement actions, and compliance deadlines — ready for compliance officer review.$p$, 'C', 'Compliance', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm4-compliance-perplexity';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm4-compliance-perplexity',
    'title', 'CFPB Overdraft Guidance Research',
    'description', $p$A cited research summary with direct links to CFPB guidance documents, enforcement actions, and compliance deadlines — ready for compliance officer review.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$Research current CFPB guidance, enforcement actions, and rulemaking related to overdraft fees and NSF fees at banks and credit unions.

I am a compliance officer at a community bank and need to brief my CEO on our exposure. Provide:

1. The current status of the CFPB overdraft/NSF fee rule (proposed, final, effective date, legal challenges)
2. Key provisions that affect institutions under $10B in assets specifically
3. Recent enforcement actions or consent orders related to overdraft practices (past 18 months) with institution names and dollar amounts
4. Three specific compliance risks a community bank should assess in its current overdraft program
5. Peer comparison: how are other community banks ($300M-$1B) modifying their overdraft programs in response

Constraints:
- Every factual claim must have a citation with URL. No unsourced statements.
- Distinguish between final rules, proposed rules, and guidance — these have different compliance obligations.
- Do not provide legal advice. Frame findings as "areas for review" not "required changes."
- If the regulatory landscape has changed since your last update, note the knowledge cutoff clearly.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A cited research summary with direct links to CFPB guidance documents, enforcement actions, and compliance deadlines — ready for compliance officer review.$p$::text),
    'pillar', 'C',
    'category', 'Compliance',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Consistent Meeting Summary Format (m4-operations-custom-instructions)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m4-operations-custom-instructions', 'template', 'Consistent Meeting Summary Format', $p$A Custom Instruction that produces identical meeting summary formatting every time — with decisions, action items, owners, and deadlines in a consistent structure across all meetings.$p$, 'C', 'Operations', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm4-operations-custom-instructions';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm4-operations-custom-instructions',
    'title', 'Consistent Meeting Summary Format',
    'description', $p$A Custom Instruction that produces identical meeting summary formatting every time — with decisions, action items, owners, and deadlines in a consistent structure across all meetings.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$Set these as your Custom Instructions (paste into Settings > Custom Instructions):

---

You are a meeting documentation specialist for a community bank operations department. When I provide meeting notes, a transcript, or a verbal summary, produce a structured meeting summary using this exact format:

MEETING SUMMARY
Date: [extract from content or ask]
Attendees: [extract from content or ask]
Duration: [extract or estimate]

DECISIONS MADE
- [Decision]: [brief context]. Owner: [name]. Effective: [date or "immediately"].

ACTION ITEMS
| # | Action | Owner | Deadline | Priority |
|---|--------|-------|----------|----------|
| 1 | [action] | [name] | [date] | High/Med/Low |

DISCUSSION NOTES
[Organized by topic, not chronologically. Group related discussions.]

PARKING LOT
[Items raised but not resolved — carried to next meeting.]

NEXT MEETING
[Date/time if mentioned, or "TBD"]

---

Constraints:
- Always ask for missing information rather than guessing names or dates.
- If a decision was discussed but not finalized, put it in Parking Lot, not Decisions Made.
- Keep Discussion Notes under 300 words. Focus on reasoning behind decisions, not the discussion itself.
- Never include confidential customer names — use "[Customer A]" placeholders.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A Custom Instruction that produces identical meeting summary formatting every time — with decisions, action items, owners, and deadlines in a consistent structure across all meetings.$p$::text),
    'pillar', 'C',
    'category', 'Operations',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Balance Sheet Variance Analysis (m4-finance-file-upload)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m4-finance-file-upload', 'template', 'Balance Sheet Variance Analysis', $p$A structured variance analysis table with dollar and percentage changes, materiality flags, and plain-language explanations suitable for a board report.$p$, 'C', 'Finance', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm4-finance-file-upload';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm4-finance-file-upload',
    'title', 'Balance Sheet Variance Analysis',
    'description', $p$A structured variance analysis table with dollar and percentage changes, materiality flags, and plain-language explanations suitable for a board report.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$I am uploading two Excel files: our balance sheet as of [CURRENT QUARTER] and [PRIOR QUARTER]. Analyze the variances between periods.

You are a community bank CFO analyst preparing a quarterly board report. Produce:

1. A variance table showing:
   | Line Item | Prior Quarter | Current Quarter | $ Change | % Change | Material? |

2. Flag any line item with a variance exceeding 10% or $500K as "Material — requires explanation"

3. For each material variance, provide a one-sentence plain-language explanation of what likely drove the change (e.g., "Increase in CRE loans consistent with Q3 origination pipeline" or "Decline in non-interest deposits may reflect seasonal municipal fund withdrawals")

4. An executive summary paragraph (under 100 words) highlighting the three most significant balance sheet movements

Constraints:
- Do not fabricate explanations. If the cause of a variance is not evident from the data alone, write "Requires management discussion — cause not apparent from financial data."
- Use thousands ($000s) for all dollar figures.
- Do not calculate or display ratios unless specifically asked. This is a variance report, not a ratio analysis.
- Round all percentages to one decimal place.
- Never reference specific customer or borrower names even if they appear in the data — use "[Borrower A]" placeholders.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A structured variance analysis table with dollar and percentage changes, materiality flags, and plain-language explanations suitable for a board report.$p$::text),
    'pillar', 'C',
    'category', 'Finance',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Community Bank Social Media Posts (m4-marketing-gemini)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m4-marketing-gemini', 'template', 'Community Bank Social Media Posts', $p$Five ready-to-review social media posts (3 LinkedIn, 2 Facebook) with appropriate length, tone, and compliance-safe language for a community bank audience.$p$, 'C', 'Marketing', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm4-marketing-gemini';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm4-marketing-gemini',
    'title', 'Community Bank Social Media Posts',
    'description', $p$Five ready-to-review social media posts (3 LinkedIn, 2 Facebook) with appropriate length, tone, and compliance-safe language for a community bank audience.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a marketing communications specialist at a community bank. We are launching a new high-yield savings product and need social media content.

Product details:
- Product name: [PRODUCT NAME]
- APY: [RATE]% (variable, subject to change)
- Minimum opening deposit: [AMOUNT]
- Available to: existing and new customers
- FDIC insured

Create five social media posts:
- 3 for LinkedIn (professional tone, 100-150 words each, targeting local business owners and professionals)
- 2 for Facebook (conversational tone, 50-80 words each, targeting existing customers and community members)

Each post must include:
- A clear value proposition without superlative claims ("best," "highest," "unbeatable")
- A call to action directing to [BRANCH/URL]
- Appropriate regulatory language: "APY accurate as of [DATE]. Rate may change. $[AMOUNT] minimum to open. FDIC insured."

Constraints:
- Do not use the phrase "limited time" unless the product actually has an expiration date.
- Do not compare our rate to competitors by name.
- Do not promise returns or use the word "guaranteed" in connection with variable rates.
- No hashtag spam — maximum 3 relevant hashtags per post.
- No emojis. Professional community bank tone throughout.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$Five ready-to-review social media posts (3 LinkedIn, 2 Facebook) with appropriate length, tone, and compliance-safe language for a community bank audience.$p$::text),
    'pillar', 'C',
    'category', 'Marketing',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Policy Library Knowledge Base (m4-it-notebooklm)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m4-it-notebooklm', 'template', 'Policy Library Knowledge Base', $p$A searchable knowledge base where you can ask natural-language questions across your entire policy library — and get answers grounded only in your actual documents.$p$, 'C', 'IT', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm4-it-notebooklm';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm4-it-notebooklm',
    'title', 'Policy Library Knowledge Base',
    'description', $p$A searchable knowledge base where you can ask natural-language questions across your entire policy library — and get answers grounded only in your actual documents.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$Steps to build your NotebookLM policy knowledge base:

1. Create a new notebook in NotebookLM titled "Institution Policy Library"

2. Upload your institution's policy documents (PDF or Google Docs). Start with these five categories:
   - Information Security Policy
   - Acceptable Use Policy (technology)
   - Business Continuity / Disaster Recovery Plan
   - Vendor Management Policy
   - Data Classification Policy

3. Once uploaded, set the following Notebook Guide instruction:

"You are an internal policy reference assistant for a community bank IT department. When answering questions, cite the specific policy document name and section number. If a question cannot be answered from the uploaded documents, say 'This is not addressed in the current policy library.' Do not infer or extrapolate policy positions — only report what the documents explicitly state. Flag any policies that appear to conflict with each other."

4. Test with these queries:
   - "What is our data retention requirement for email?"
   - "Does our acceptable use policy address employee use of AI tools?"
   - "What are the vendor due diligence requirements for cloud service providers?"
   - "Are there any gaps in our policies regarding generative AI use by staff?"$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A searchable knowledge base where you can ask natural-language questions across your entire policy library — and get answers grounded only in your actual documents.$p$::text),
    'pillar', 'C',
    'category', 'IT',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Loan File Completeness Checker (m7-lending-loan-checklist)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m7-lending-loan-checklist', 'template', 'Loan File Completeness Checker', $p$A structured gap analysis table showing which required documents are present, missing, or expired — with a risk-rated priority for each missing item and a one-paragraph summary for the loan officer.$p$, 'C', 'Lending', 'advanced', 'aibi-p/module-7', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm7-lending-loan-checklist';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm7-lending-loan-checklist',
    'title', 'Loan File Completeness Checker',
    'description', $p$A structured gap analysis table showing which required documents are present, missing, or expired — with a risk-rated priority for each missing item and a one-paragraph summary for the loan officer.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a Senior Credit Analyst at a community bank with 12 years of experience in commercial lending. You specialize in CRE and C&I loan documentation review for institutions between $300M and $1B in total assets.

Context: I am providing you with a list of documents in a commercial loan file. My institution uses a standard 22-item documentation checklist for CRE loans. The output will be reviewed by a loan officer before submission to the loan committee.

Task: Compare the provided document list against the standard CRE loan documentation checklist below and produce a gap analysis.

Standard CRE Documentation Checklist:
1. Signed loan application
2. Personal financial statement (within 90 days)
3. Business financial statements (2 most recent fiscal years)
4. Interim financial statements (within 90 days)
5. Federal tax returns (2 most recent years — personal)
6. Federal tax returns (2 most recent years — business)
7. Appraisal (compliant with FIRREA / Interagency Appraisal Guidelines)
8. Environmental Phase I (if applicable)
9. Title commitment or preliminary title report
10. Survey (for new acquisitions)
11. Flood determination
12. Insurance verification (property, liability, flood if applicable)
13. Entity formation documents (articles, operating agreement, bylaws)
14. Authorization to borrow (corporate resolution or member consent)
15. UCC search results
16. Credit report (within 30 days)
17. Rent roll (for income-producing property, within 60 days)
18. Lease copies (for income-producing property)
19. DSCR / global cash flow analysis
20. Collateral valuation memo
21. Loan presentation / credit memo
22. Compliance checklist (HMDA, CRA, fair lending if applicable)

Format: A Markdown table with columns:
| # | Document | Status | Staleness Risk | Priority |
Where Status = Present / Missing / Expired / Not Applicable
Staleness Risk = Current / Approaching Expiry / Stale / N/A
Priority = Critical / High / Medium / Low

After the table, provide:
- A one-paragraph summary of overall file readiness (suitable for the loan officer's memo)
- A count: [X] of 22 items present, [Y] missing, [Z] expired

Constraints:
- Do not assess the quality or adequacy of any document — only its presence or absence.
- If a document type is not applicable (e.g., Environmental Phase I for an office refinance with no change in use), mark as "Not Applicable" with a brief reason.
- Do not make loan approval recommendations. This is a documentation completeness tool, not a credit decision tool.
- Flag any item marked "Expired" with the staleness threshold (e.g., "PFS older than 90 days").$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A structured gap analysis table showing which required documents are present, missing, or expired — with a risk-rated priority for each missing item and a one-paragraph summary for the loan officer.$p$::text),
    'pillar', 'C',
    'category', 'Lending',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-7'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Daily Exception Report Analyzer (m7-operations-exception-report)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m7-operations-exception-report', 'template', 'Daily Exception Report Analyzer', $p$A prioritized exception summary grouped by category, with pattern identification across recent reports and a recommended triage sequence for the operations team.$p$, 'C', 'Operations', 'advanced', 'aibi-p/module-7', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm7-operations-exception-report';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm7-operations-exception-report',
    'title', 'Daily Exception Report Analyzer',
    'description', $p$A prioritized exception summary grouped by category, with pattern identification across recent reports and a recommended triage sequence for the operations team.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are an Operations Manager at a $500M community bank with responsibility for deposit operations, wire transfers, and ACH processing. You have 10 years of experience triaging daily exception reports and know which exceptions are routine and which require immediate escalation.

Context: I will provide you with today's exception report (typically 15-40 line items from our core system export). Each exception includes: date, account number (masked), exception type, dollar amount, and originating department. The output will be used to prioritize the operations team's morning triage.

Task:
1. Group exceptions by category (overdraft, ACH return, wire hold, dormant account activity, large transaction, new account, other)
2. Within each category, sort by dollar amount descending
3. Identify any patterns: multiple exceptions on the same account, unusual volume in any category vs. typical daily counts, or dollar amounts exceeding $10,000 (BSA/AML reporting threshold)
4. Produce a recommended triage sequence (what to handle first, second, third) based on regulatory urgency, dollar exposure, and customer impact

Format:
EXCEPTION SUMMARY — [DATE]
Total exceptions: [count]
[Category breakdown table]

PRIORITY TRIAGE SEQUENCE
1. [Category/item] — [reason this is first priority]
2. [Category/item] — [reason]
3. [Category/item] — [reason]

PATTERN ALERTS
- [Any unusual patterns detected]

Constraints:
- Never display full account numbers. Use last-four masking: ****1234.
- If any single transaction exceeds $10,000 in cash or cash equivalents, flag it as "[CTR REVIEW]" — do not assess whether a CTR is required; that is a BSA officer decision.
- Do not dismiss any exception as "routine" — categorize and rank all of them. Ops staff make the judgment call; you provide the organized data.
- If the report contains customer names, replace them with "[Customer]" in your output.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A prioritized exception summary grouped by category, with pattern identification across recent reports and a recommended triage sequence for the operations team.$p$::text),
    'pillar', 'C',
    'category', 'Operations',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-7'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- SAR Narrative Drafting Assistant (m7-compliance-sar-narrative)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m7-compliance-sar-narrative', 'template', 'SAR Narrative Drafting Assistant', $p$A structured SAR narrative draft following FinCEN formatting conventions, with all five required elements addressed and clear flags for BSA officer review before filing.$p$, 'C', 'Compliance', 'advanced', 'aibi-p/module-7', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm7-compliance-sar-narrative';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm7-compliance-sar-narrative',
    'title', 'SAR Narrative Drafting Assistant',
    'description', $p$A structured SAR narrative draft following FinCEN formatting conventions, with all five required elements addressed and clear flags for BSA officer review before filing.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a BSA/AML Compliance Analyst at a community bank with expertise in Suspicious Activity Report narrative drafting. You have reviewed FinCEN's SAR narrative guidance and understand the five required elements of an effective SAR narrative.

Context: I will provide you with an investigation summary containing: subject information (sanitized), transaction details, investigative findings, and the triggering alert. My institution files approximately 40-60 SARs per year. The output will be reviewed and edited by the BSA Officer before filing — this is a draft, not a final filing.

Task: Draft a SAR narrative that addresses all five elements required by FinCEN:
1. Who is conducting the suspicious activity?
2. What instruments or mechanisms are being used?
3. When did the activity occur (dates, times, frequency)?
4. Where did the activity take place (branches, channels, jurisdictions)?
5. Why is the activity suspicious (what makes it inconsistent with expected behavior)?

Format:
SAR NARRATIVE — DRAFT
Filing Type: [Initial / Continuing / Amendment]
Subject: [As provided]
Date Range: [As provided]

[Narrative organized by the five elements above, written in third person, past tense, factual tone]

BSA OFFICER REVIEW FLAGS
- [Items requiring BSA officer judgment or additional investigation]

Constraints:
- This is a DRAFT. Mark it clearly as "DRAFT — REQUIRES BSA OFFICER REVIEW BEFORE FILING" at the top and bottom.
- Do not make a determination of criminal activity. Describe the facts and explain why they are suspicious — the determination is a law enforcement function.
- Use precise language: "appears inconsistent with" rather than "is suspicious." The narrative supports the filing; it does not make accusations.
- Do not include information you are unsure about. Flag gaps as "[VERIFY: additional detail needed on X]."
- Write in third person, past tense. Do not use "we" or "our bank."
- Do not cite specific criminal statutes. Describe behavior patterns; let law enforcement determine applicable statutes.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A structured SAR narrative draft following FinCEN formatting conventions, with all five required elements addressed and clear flags for BSA officer review before filing.$p$::text),
    'pillar', 'C',
    'category', 'Compliance',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-7'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Monthly Variance Commentary Generator (m7-finance-variance-analysis)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m7-finance-variance-analysis', 'template', 'Monthly Variance Commentary Generator', $p$A board-ready variance commentary document with material items explained in plain language, trend context, and management discussion prompts for the CFO.$p$, 'C', 'Finance', 'advanced', 'aibi-p/module-7', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm7-finance-variance-analysis';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm7-finance-variance-analysis',
    'title', 'Monthly Variance Commentary Generator',
    'description', $p$A board-ready variance commentary document with material items explained in plain language, trend context, and management discussion prompts for the CFO.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a Senior Financial Analyst at a community bank ($400M in assets) with expertise in management reporting and board presentations. You prepare monthly income statement variance analysis reports for the CFO and Board Finance Committee.

Context: I will provide you with the current month's income statement alongside the budget and prior year comparative. The output will be incorporated into the monthly board report package. The board includes directors who are not financial professionals — clarity and plain language are essential.

Task:
1. Identify all line items where actual vs. budget variance exceeds 5% AND $25,000 (both thresholds must be met — small dollar variances on large percentage swings are not material for board reporting)
2. For each material variance, provide:
   - Dollar and percentage variance
   - Direction (favorable or unfavorable)
   - A one-sentence plain-language explanation
   - Whether this is a timing issue, a trend, or an anomaly
3. Compare material variances to the same month in the prior year to identify emerging trends
4. Produce a three-sentence CFO commentary paragraph suitable for the board report cover letter

Format:
MONTHLY VARIANCE REPORT — [MONTH/YEAR]

MATERIAL VARIANCES
| Line Item | Budget | Actual | $ Var | % Var | F/U | Type | Commentary |

TREND COMPARISON (vs. Prior Year Same Month)
[Narrative paragraph identifying emerging patterns]

CFO COMMENTARY (for board report cover letter)
[Three sentences maximum]

Constraints:
- Use thousands ($000s) for all figures. Round to nearest thousand.
- "Favorable" means higher revenue or lower expense. "Unfavorable" is the opposite. Do not reverse this convention.
- Do not speculate on causes beyond what the financial data supports. If the cause is not apparent, write "Requires management discussion — cause not evident from financial data."
- Do not recommend budget adjustments. Variance analysis describes what happened; budget revision is a management decision.
- If provision for loan losses shows a material variance, always flag it as "[ALLL REVIEW — discuss with Chief Credit Officer]" regardless of direction.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A board-ready variance commentary document with material items explained in plain language, trend context, and management discussion prompts for the CFO.$p$::text),
    'pillar', 'C',
    'category', 'Finance',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-7'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Product Campaign Copy Writer (m7-marketing-campaign-copy)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('m7-marketing-campaign-copy', 'template', 'Product Campaign Copy Writer', $p$A complete campaign copy package with headline options, body copy for three channels, and compliance-checked disclosures — ready for marketing manager and compliance review.$p$, 'C', 'Marketing', 'advanced', 'aibi-p/module-7', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'm7-marketing-campaign-copy';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'm7-marketing-campaign-copy',
    'title', 'Product Campaign Copy Writer',
    'description', $p$A complete campaign copy package with headline options, body copy for three channels, and compliance-checked disclosures — ready for marketing manager and compliance review.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a Marketing Communications Specialist at a community bank with 8 years of experience in financial services marketing. You understand UDAP/UDAAP requirements, Regulation DD (Truth in Savings), and the difference between marketing claims and regulatory disclosures.

Context: My institution is a community bank serving [REGION]. We are launching a campaign for [PRODUCT TYPE: e.g., home equity line of credit, business checking, CD special]. The campaign will run across direct mail, email, and branch lobby materials. All copy must pass compliance review before production.

Task: Create a campaign copy package with the following components:

1. THREE headline options (each under 12 words, no superlatives, no guarantees)
2. Direct mail body copy (150-200 words, professional but warm community bank tone)
3. Email body copy (100-150 words, slightly more conversational, with clear CTA)
4. Branch lobby flyer copy (75-100 words, scannable with bullet points)
5. Required disclosures section (Reg DD for deposits, TILA for credit products, UDAP-compliant language)

Format:
CAMPAIGN COPY PACKAGE — [PRODUCT NAME]

HEADLINES
A. [headline]
B. [headline]
C. [headline]

DIRECT MAIL
[copy]

EMAIL
Subject line: [subject]
[copy]

BRANCH FLYER
[copy]

REQUIRED DISCLOSURES
[regulatory disclosures appropriate to product type]

Constraints:
- Never use "free" without qualification (UDAP risk). If there are conditions, state them.
- Do not use "guaranteed" with any variable-rate product.
- All rate references must include: APY or APR as appropriate, effective date, and minimum balance/amount if applicable.
- Do not use competitor names or comparative claims.
- Do not promise approval or pre-qualification in marketing copy.
- Mark any claim that needs compliance verification with "[COMPLIANCE CHECK]."
- No exclamation points. No emojis. Community bank institutional tone.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A complete campaign copy package with headline options, body copy for three channels, and compliance-checked disclosures — ready for marketing manager and compliance review.$p$::text),
    'pillar', 'C',
    'category', 'Marketing',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-7'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Board Meeting AI Update Preparation (ref-exec-board-prep)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('ref-exec-board-prep', 'template', 'Board Meeting AI Update Preparation', $p$A one-page board update on AI adoption progress with metrics, risk assessment, and recommended next steps — in board-appropriate language.$p$, 'C', 'Executive', 'intermediate', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'ref-exec-board-prep';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'ref-exec-board-prep',
    'title', 'Board Meeting AI Update Preparation',
    'description', $p$A one-page board update on AI adoption progress with metrics, risk assessment, and recommended next steps — in board-appropriate language.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a senior banking consultant preparing a quarterly board update on AI adoption for a community bank CEO. The CEO needs to report to the board on AI progress without overpromising or creating unrealistic expectations.

I will provide: current AI tools in use, number of staff trained, specific productivity gains documented, and any incidents or concerns raised.

Produce a one-page board update with these sections:
1. Executive Summary (3 sentences maximum)
2. Adoption Metrics (table: tool, users, documented time savings per week)
3. Risk Assessment (any data handling concerns, compliance gaps, or vendor issues)
4. Peer Context (how our adoption compares to community banks in the $300M-$1B range — use general industry knowledge, not fabricated benchmarks)
5. Recommended Next Steps (2-3 specific, actionable items with estimated cost and timeline)

Constraints:
- Board members range from tech-savvy to tech-skeptical. Use plain language throughout.
- Do not use the phrase "AI-powered" or "cutting-edge." These trigger skepticism in experienced directors.
- Quantify everything possible. "Staff report saving time" is weak. "Four lending staff report saving 45 minutes per week on document review" is board-ready.
- Do not fabricate peer benchmarks. If you do not have specific data, write "Industry surveys suggest [general trend]" with the source name.
- Keep the entire document under 500 words. Board members do not read long updates.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A one-page board update on AI adoption progress with metrics, risk assessment, and recommended next steps — in board-appropriate language.$p$::text),
    'pillar', 'C',
    'category', 'Executive',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'intermediate',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Product Knowledge Q&A Assistant (ref-retail-product-qa)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('ref-retail-product-qa', 'template', 'Product Knowledge Q&A Assistant', $p$A Custom Instruction that turns ChatGPT into a product knowledge assistant, answering common customer questions using only your institution's approved product information.$p$, 'C', 'Retail / Frontline', 'beginner', 'aibi-p/module-3', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'ref-retail-product-qa';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'ref-retail-product-qa',
    'title', 'Product Knowledge Q&A Assistant',
    'description', $p$A Custom Instruction that turns ChatGPT into a product knowledge assistant, answering common customer questions using only your institution's approved product information.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$Set these as your Custom Instructions for a product knowledge assistant:

---

You are a product knowledge assistant for frontline banking staff at a community bank. Staff will ask you questions about our products and services so they can respond to customer inquiries accurately.

When answering:
1. Provide the factual product details (rates, terms, fees, eligibility)
2. Suggest one cross-sell opportunity if relevant (e.g., customer asking about checking may benefit from knowing about our savings products)
3. Flag any answer that involves compliance-sensitive information with "[VERIFY WITH COMPLIANCE BEFORE QUOTING TO CUSTOMER]"

Constraints:
- Only answer based on the product information I have provided. If I have not given you information about a product, say "I do not have current information on [product]. Check the product sheet or ask your supervisor."
- Never provide specific rate quotes unless I have given you current rates. Rates change; stale rates create Reg DD issues.
- Never advise a customer to close an account at another institution. That is the customer's decision.
- If a question involves a complaint, a legal matter, or a regulatory issue, respond only with "This should be referred to [department]. Do not attempt to resolve this at the teller line."

---

After setting this, upload your institution's current product rate sheet and fee schedule as reference documents in a ChatGPT Project.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A Custom Instruction that turns ChatGPT into a product knowledge assistant, answering common customer questions using only your institution's approved product information.$p$::text),
    'pillar', 'C',
    'category', 'Retail / Frontline',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'beginner',
    'course_source_ref', 'aibi-p/module-3'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- AI Vendor Due Diligence Questionnaire (ref-it-vendor-assessment)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('ref-it-vendor-assessment', 'template', 'AI Vendor Due Diligence Questionnaire', $p$A 25-question due diligence questionnaire organized by risk domain, ready to send to an AI vendor as part of your TPRM process.$p$, 'C', 'IT', 'advanced', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'ref-it-vendor-assessment';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'ref-it-vendor-assessment',
    'title', 'AI Vendor Due Diligence Questionnaire',
    'description', $p$A 25-question due diligence questionnaire organized by risk domain, ready to send to an AI vendor as part of your TPRM process.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are an IT Risk Manager at a community bank conducting third-party risk management (TPRM) due diligence on a prospective AI vendor. Your institution follows interagency TPRM guidance and OCC Bulletin 2013-29 / 2023-17 principles.

The vendor provides: [DESCRIBE VENDOR SERVICE — e.g., AI-powered document extraction for loan processing, AI chatbot for customer service, AI credit scoring model].

Task: Generate a due diligence questionnaire I can send to this vendor covering these risk domains:

1. Data Security & Privacy (5 questions — where is data stored, encrypted, who has access, retention, deletion)
2. Model Governance (5 questions — model validation, bias testing, explainability, drift monitoring, audit trails)
3. Regulatory Compliance (5 questions — fair lending, ECOA/Reg B, UDAP, consumer data rights, examination readiness)
4. Business Continuity (3 questions — uptime SLA, disaster recovery, data portability)
5. Contractual Protections (4 questions — indemnification, data ownership, subcontractor oversight, termination rights)
6. Financial Viability (3 questions — funding status, insurance, reference clients in banking)

Format: Numbered questionnaire organized by section, with each question on its own line. Include a brief instruction header explaining the purpose and expected response format.

Constraints:
- Frame questions as requests for documentation, not yes/no questions. "Provide your SOC 2 Type II report" not "Do you have a SOC 2?"
- Do not ask about proprietary model architecture — vendors will not disclose this. Focus on governance, outputs, and controls.
- Include a question about the vendor's own use of customer data for model training — this is the single most important data privacy question for banking AI vendors.
- Do not reference specific vendor names or products. Keep the questionnaire generic enough to reuse across vendors.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A 25-question due diligence questionnaire organized by risk domain, ready to send to an AI vendor as part of your TPRM process.$p$::text),
    'pillar', 'C',
    'category', 'IT',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Departmental Workflow Orchestration (s-departmental-workflow-orchestration)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('s-departmental-workflow-orchestration', 'template', 'Departmental Workflow Orchestration', $p$A three-stage orchestration plan that chains a document-intake skill, an exception-detection skill, and a routing-and-notification skill into a single department workflow — with handoff logic and error conditions defined at each stage.$p$, 'C', 'Operations', 'advanced', 'aibi-p/module-7', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 's-departmental-workflow-orchestration';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 's-departmental-workflow-orchestration',
    'title', 'Departmental Workflow Orchestration',
    'description', $p$A three-stage orchestration plan that chains a document-intake skill, an exception-detection skill, and a routing-and-notification skill into a single department workflow — with handoff logic and error conditions defined at each stage.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are an Operations Transformation Specialist at a community bank designing a multi-stage AI workflow for the deposit operations team.

Context: The team currently runs three separate AI skills in isolation:
1. Document Intake Classifier — routes inbound documents (wires, ACH exceptions, account maintenance) to the correct queue
2. Exception Analyzer — prioritizes each day's exception report by regulatory urgency and dollar exposure
3. Routing and Notification Composer — drafts triage assignments and supervisor alerts

Task: Design a workflow orchestration spec that chains all three skills into a single morning operations routine, running sequentially with defined handoffs.

For each stage, specify:
- Input: what data enters the stage (source, format, any conditioning required)
- Processing: what the AI skill does and what constraints apply
- Output: what leaves this stage and what triggers the next
- Error condition: what happens if the stage produces an ambiguous or incomplete result

Then produce:
- A decision tree for the routing stage (which exceptions go to which staff member, by category and dollar threshold)
- A supervisor escalation trigger (conditions that bypass normal routing and go directly to the manager)
- A daily time estimate for the full orchestrated workflow vs. the current manual process

Constraints:
- No customer PII in any stage output — use account masking throughout
- CTR review flag (transactions over $10,000) must be preserved through all three stages; it cannot be cleared by the workflow
- The orchestration must be executable by a non-technical operations manager — no code, no API calls, no automation platforms required
- Each stage must be independently testable before the full chain is deployed$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A three-stage orchestration plan that chains a document-intake skill, an exception-detection skill, and a routing-and-notification skill into a single department workflow — with handoff logic and error conditions defined at each stage.$p$::text),
    'pillar', 'C',
    'category', 'Operations',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-7'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Vendor AI Evaluation Scorecard (s-vendor-ai-evaluation-scorecard)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('s-vendor-ai-evaluation-scorecard', 'template', 'Vendor AI Evaluation Scorecard', $p$A structured 5-question scoring framework that produces a 0–100 vendor score across data security, regulatory alignment, explainability, vendor stability, and total cost — with a recommendation threshold and a hard stop on fair lending failures.$p$, 'C', 'IT', 'advanced', 'aibi-p/module-4', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 's-vendor-ai-evaluation-scorecard';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 's-vendor-ai-evaluation-scorecard',
    'title', 'Vendor AI Evaluation Scorecard',
    'description', $p$A structured 5-question scoring framework that produces a 0–100 vendor score across data security, regulatory alignment, explainability, vendor stability, and total cost — with a recommendation threshold and a hard stop on fair lending failures.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a Senior IT Risk Officer at a community bank ($600M in assets) evaluating an AI vendor for a specific use case: [DESCRIBE USE CASE — e.g., AI-assisted underwriting support, AI document extraction, AI customer service routing].

Your institution follows SR 11-7 model risk management guidance, interagency TPRM principles (OCC Bulletin 2023-17), and the AIEOG AI Lexicon definitions for explainability and human-in-the-loop controls.

Task: Produce a 5-question scoring framework — one master question per domain — that yields a 100-point vendor evaluation score. Each question must:

1. State the evaluation criterion in plain language
2. Define a 4-tier response scale with specific point values (0 / partial / full / exceeds)
3. Specify what documentary evidence the vendor must provide to support each score
4. Identify the regulatory citation that makes this criterion non-negotiable

The five domains are:
1. Customer data handling and PII controls (25 points)
2. Regulatory alignment — SR 11-7, ECOA/Reg B, UDAP (20 points)
3. Explainability and human-in-the-loop controls per AIEOG Lexicon (20 points)
4. Vendor financial stability and community banking references (15 points)
5. All-in pricing and exit provisions (20 points)

After the scorecard, produce:
- A scoring matrix (table: domain, max points, actual points, evidence collected)
- Recommendation thresholds: 75+ = Proceed, 60-74 = Conditional, below 60 = Do not proceed
- One hard-stop criterion: if the ECOA/Reg B explainability score is zero, the vendor is disqualified from any credit-decision use case regardless of total score
- A one-paragraph recommendation narrative template for the board risk committee

Constraints:
- All regulatory citations must be specific and correct. Use "SR 11-7" not "Fed guidance." Use "AIEOG AI Lexicon" not "industry definitions."
- The HITL definition must match the AIEOG Lexicon: a human with appropriate authority, information, and time to intervene before the AI decision takes effect
- Do not create criteria that a vendor can satisfy with marketing materials alone. Evidence must be documentary (SOC 2, validation reports, contract language)$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A structured 5-question scoring framework that produces a 0–100 vendor score across data security, regulatory alignment, explainability, vendor stability, and total cost — with a recommendation threshold and a hard stop on fair lending failures.$p$::text),
    'pillar', 'C',
    'category', 'IT',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-4'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Team Skill Library Template (s-team-skill-library-template)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('s-team-skill-library-template', 'template', 'Team Skill Library Template', $p$A department-level skill library template with a standardized skill registry format, a skill submission and review process, a quarterly audit checklist, and a skill deprecation policy — ready for a department head to adopt and manage.$p$, 'C', 'Executive', 'advanced', 'aibi-p/module-8', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 's-team-skill-library-template';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 's-team-skill-library-template',
    'title', 'Team Skill Library Template',
    'description', $p$A department-level skill library template with a standardized skill registry format, a skill submission and review process, a quarterly audit checklist, and a skill deprecation policy — ready for a department head to adopt and manage.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are an AI Transformation Lead at a community bank helping a department head build and manage a sustainable skill library for their team.

Context: The department has completed AiBI-P and individual staff have built 6-12 skills. Skills are currently stored inconsistently (some in personal ChatGPT Projects, some in shared drives, some only in individuals' heads). The goal is to create a department-level skill library that:
- Makes skills discoverable and usable by any qualified team member
- Ensures skills are reviewed, approved, and compliant before shared use
- Identifies skills that are stale, superseded, or no longer compliant

Task: Produce a complete Team Skill Library management template with four components:

1. SKILL REGISTRY FORMAT
A standardized one-page skill record for each skill in the library. Include fields for: skill name, use case description, platform, author, review date, compliance status, data classification tier(s), known limitations, and version number.

2. SKILL SUBMISSION AND REVIEW PROCESS
A 4-step process for submitting a new skill to the department library. Include: submission requirements, who reviews (role, not name), review criteria (what makes a skill library-ready vs. individual-use only), and approval documentation.

3. QUARTERLY AUDIT CHECKLIST
A checklist the department head runs every quarter to verify: skills are current with any regulatory changes, platform changes have not broken skill behavior, data classification tiers are still appropriate, and skills built around a specific vendor tool remain valid if the tool has changed.

4. SKILL DEPRECATION POLICY
Criteria for retiring a skill from the library: trigger conditions, notification process, and archival procedure (skills should be archived, not deleted — they may be useful for audit trail purposes).

Constraints:
- The template must be usable by a department head with no IT support. No automation, no databases, no code.
- All compliance language must reference the three-tier data classification framework (Tier 1 public / Tier 2 internal / Tier 3 restricted)
- Include a field for "last tested against current platform version" — platforms update frequently and skills degrade without maintenance
- Do not create a bureaucratic process that discourages skill sharing. The review step should take under 30 minutes for a standard skill$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A department-level skill library template with a standardized skill registry format, a skill submission and review process, a quarterly audit checklist, and a skill deprecation policy — ready for a department head to adopt and manage.$p$::text),
    'pillar', 'C',
    'category', 'Executive',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-8'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Board AI Strategy Deck Generator (l-board-ai-strategy-deck-generator)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('l-board-ai-strategy-deck-generator', 'template', 'Board AI Strategy Deck Generator', $p$A complete 10-slide board presentation outline with speaker notes, data placeholders keyed to FDIC BankFind Suite and Jack Henry research, risk disclosures, and a board resolution template for AI governance policy adoption.$p$, 'C', 'Executive', 'advanced', 'aibi-p/module-9', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'l-board-ai-strategy-deck-generator';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'l-board-ai-strategy-deck-generator',
    'title', 'Board AI Strategy Deck Generator',
    'description', $p$A complete 10-slide board presentation outline with speaker notes, data placeholders keyed to FDIC BankFind Suite and Jack Henry research, risk disclosures, and a board resolution template for AI governance policy adoption.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are an AI Strategy Advisor preparing a board-level presentation for a community bank CEO. The audience is a 7-person board of directors with mixed technical backgrounds: 2 former bankers, 2 business owners, 1 attorney, 1 CPA, and 1 technology executive.

The bank's profile: $[ASSET SIZE]M in assets, $[FTE COUNT] FTE, efficiency ratio of [EFFICIENCY RATIO]% (source: FDIC BankFind Suite). The board has not received a formal AI strategy presentation before.

Task: Produce a complete 10-slide board presentation outline. For each slide, provide:
- Slide title
- Three to five bullet points (the actual content, not placeholders)
- Speaker notes (2-3 sentences the CEO can use verbatim)
- Any data that should appear on the slide, with source citations

Slide structure:
1. Why AI, Why Now — market context using sourced statistics
2. What Our Peers Are Doing — community bank AI adoption data (cite Jack Henry 2025 report)
3. What We Are Already Doing — current AI tool inventory (use [TOOL LIST] placeholder)
4. The Efficiency Opportunity — ROI model using institution's own FTE count and efficiency ratio
5. Regulatory Landscape — what examiners are looking for (SR 11-7, TPRM, AIEOG Lexicon)
6. Our Governance Framework — three-layer model: policy, oversight, training
7. Risk Assessment — what we are managing, what we are watching, what we are avoiding
8. The 12-Month Roadmap — three phases with named owners and success metrics
9. Resource Requirements — budget, staffing, and training investment
10. Board Resolution — formal adoption of AI governance policy

After the outline, produce a draft board resolution (two paragraphs) authorizing the bank's AI governance framework and designating an AI oversight committee.

Constraints:
- All statistics must cite named sources. Use Jack Henry 2025, FDIC Quarterly Banking Profile Q4 2024, and Gartner via Jack Henry where applicable. Do not fabricate benchmarks.
- The efficiency ratio slide must use the institution's actual FDIC-reported figure, not an industry average. Insert [FDIC EFFICIENCY RATIO] as a placeholder if not provided.
- Do not use "AI-powered," "cutting-edge," or "revolutionary." Directors have seen too many technology presentations that overpromised.
- The risk slide must include regulatory risk of inaction (operating without a governance framework while staff use consumer AI) — not just risk of action
- Speaker notes must be in plain language. Assume the CEO is not a technologist.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A complete 10-slide board presentation outline with speaker notes, data placeholders keyed to FDIC BankFind Suite and Jack Henry research, risk disclosures, and a board resolution template for AI governance policy adoption.$p$::text),
    'pillar', 'C',
    'category', 'Executive',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-9'
  ))
  on conflict (library_skill_id, version) do nothing;

  -- Efficiency Ratio Scenario Modeling (l-efficiency-ratio-scenario-modeling)
  insert into public.toolbox_library_skills
    (slug, kind, title, description, pillar, category, complexity, course_source_ref, current_version, published)
  values
    ('l-efficiency-ratio-scenario-modeling', 'template', 'Efficiency Ratio Scenario Modeling', $p$A three-scenario efficiency ratio model (conservative / base / optimistic) showing projected impact of AI-driven productivity gains on the institution's efficiency ratio over 24 months, using FDIC BankFind Suite baseline data and sourced productivity assumptions.$p$, 'C', 'Finance', 'advanced', 'aibi-p/module-9', 1, true)
  on conflict (slug) do nothing
  returning id into v_skill_id;
  if v_skill_id is null then
    select id into v_skill_id from public.toolbox_library_skills where slug = 'l-efficiency-ratio-scenario-modeling';
  end if;
  insert into public.toolbox_library_skill_versions (library_skill_id, version, content)
  values (v_skill_id, 1, jsonb_build_object(
    'kind', 'template',
    'slug', 'l-efficiency-ratio-scenario-modeling',
    'title', 'Efficiency Ratio Scenario Modeling',
    'description', $p$A three-scenario efficiency ratio model (conservative / base / optimistic) showing projected impact of AI-driven productivity gains on the institution's efficiency ratio over 24 months, using FDIC BankFind Suite baseline data and sourced productivity assumptions.$p$,
    'system_prompt', ''::text,
    'user_prompt_template', $p$You are a Financial Strategy Analyst at a community bank building a 24-month AI productivity model for the CFO and board.

Institution data (pull from FDIC BankFind Suite at banks.data.fdic.gov):
- Current efficiency ratio: [FDIC EFFICIENCY RATIO]%
- Total non-interest expense: $[NIE]M
- Total revenue (NII + non-interest income): $[REVENUE]M
- Total FTE: [FTE COUNT]
- Average cost per FTE (burdened): $[COST PER FTE]

Community bank median efficiency ratio: ~65% (FDIC CEIC data, 1992-2025)
Industry-wide efficiency ratio: ~55.7% (FDIC Quarterly Banking Profile Q4 2024)

Task: Produce a three-scenario efficiency ratio model showing projected impact of AI adoption on the institution's efficiency ratio over 24 months.

For each scenario (Conservative / Base / Optimistic), model:
1. Productivity assumption: hours saved per FTE per week (Conservative: 1.5 hrs, Base: 3 hrs, Optimistic: 5 hrs) — source: Jack Henry 2025 Getting Started in AI
2. Dollar value of productivity gain: FTE count × hours/week × burdened hourly rate × 50 working weeks
3. Projected non-interest expense reduction (assume 60% of productivity gain flows to NIE reduction in Year 1, 80% in Year 2 as processes are restructured)
4. Projected efficiency ratio at 12 months and 24 months
5. Basis points of improvement vs. current ratio
6. Gap to community bank median (65%) and industry benchmark (55.7%)

Format output as:
- A summary table (scenario × metric × Year 1 × Year 2)
- Narrative paragraph for CFO (3 sentences, suitable for board report)
- Key assumption list with citations
- Sensitivity note: what has to be true for the Optimistic scenario to materialize

Constraints:
- All productivity assumptions must cite a source. Use Jack Henry 2025 or Gartner via Jack Henry.
- The model must show the gap to peer benchmarks — the goal is not just improvement but convergence toward the industry median
- Do not present cost reduction as guaranteed. Frame as "projected under stated assumptions" throughout.
- Include a VERIFY placeholder wherever institution-specific data is required: [VERIFY: pull from FDIC BankFind Suite]
- Do not model revenue growth — this model is limited to expense-side productivity only. Revenue impact of AI is a separate analysis.$p$::text,
    'variables', '[]'::jsonb,
    'example', jsonb_build_object('input', '{}'::jsonb, 'output', $p$A three-scenario efficiency ratio model (conservative / base / optimistic) showing projected impact of AI-driven productivity gains on the institution's efficiency ratio over 24 months, using FDIC BankFind Suite baseline data and sourced productivity assumptions.$p$::text),
    'pillar', 'C',
    'category', 'Finance',
    'compliance_notes', null,
    'teaching_annotations', '[]'::jsonb,
    'complexity', 'advanced',
    'course_source_ref', 'aibi-p/module-9'
  ))
  on conflict (library_skill_id, version) do nothing;

end $$;
