// SCRIPT: "Safe AI Use in Banking" — authored from real aibi content
// (the Module 9 Safety Lab scenarios in
//  src/app/courses/foundation/program/_lib/safetyLabData.ts) and tied to the
// free download `public/downloads/aibi-safe-ai-use-guide.pdf`.
//
// This file IS the editable artifact. Rewrite the narration, reorder sections,
// change durations — the video re-renders to match. To make a video about a
// different resource, copy this file and rewrite it.

import { VideoScript } from "../scripted/types";
// Generated by `npm run voiceover` (scripts/generate-voiceover.mjs). Until then
// `enabled` is false and the video plays silent with kinetic captions.
import narration from "./safe-ai-use.narration.json";

const baseScript: VideoScript = {
  title: "Safe AI Use in Banking",
  subtitle: "A field guide in four moves",
  resource: {
    name: "The SAFE AI Use Guide",
    kicker: "Free download",
    url: "aibi.org/resources",
  },

  sections: [
    {
      id: "hook",
      kind: "hook",
      narration:
        "The AI gave a perfect answer. Polished, confident, friendly — and completely wrong. In a bank, a good-looking answer is not the same as a safe one.",
      seconds: 7,
    },
    {
      id: "frame",
      kind: "frame",
      kicker: "The rule",
      headline: "Green · Yellow · Red",
      narration:
        "Every AI task in a bank sits in a zone. Green: go. Yellow: check it before you trust it. Red: a person has to decide.",
      seconds: 7,
    },
    {
      id: "confident-wrong",
      kind: "scenario",
      zone: "yellow",
      kicker: "Yellow · Check",
      headline: "The confident wrong answer",
      narration:
        "Asked for a CD early-withdrawal penalty, the assistant invented a number — because the prompt gave it no source. The fix: ground it in the real schedule, and require confirm-before-quoting.",
      seconds: 10,
    },
    {
      id: "the-leak",
      kind: "scenario",
      zone: "red",
      kicker: "Red · Protect data",
      headline: "The leak",
      narration:
        "A hardship letter drafted beautifully — right after a banker pasted in a full SSN, account number, and date of birth the task never needed. The fix: strip it to only what the draft requires. A first name and the situation.",
      seconds: 10,
    },
    {
      id: "line-crosser",
      kind: "scenario",
      zone: "red",
      kicker: "Red · Escalate",
      headline: "The line-crosser",
      narration:
        "Should we approve this overdraft? The AI said yes. But approving access to money is a red-zone call. Let AI summarize the factors and prepare the escalation — a person decides, and owns it.",
      seconds: 10,
    },
    {
      id: "recap",
      kind: "recap",
      kicker: "Four moves",
      headline: "Frame · Check · Protect · Escalate",
      narration:
        "Frame the task. Check the facts. Protect the data. Escalate the decision. Four moves that keep AI both useful and safe.",
      seconds: 7,
    },
  ],

};

// If voiceover has been generated, overlay each section's measured duration and
// audio path so captions stay synced to the spoken track. Otherwise this is a
// no-op and the video plays silent. This is the seam the generator writes into.
function withNarration(script: VideoScript): VideoScript {
  if (!narration.enabled) return script;
  const map = narration.sections as Record<
    string,
    { seconds: number; audio: string }
  >;
  return {
    ...script,
    sections: script.sections.map((s) =>
      map[s.id] ? { ...s, seconds: map[s.id].seconds, audio: map[s.id].audio } : s,
    ),
  };
}

export const safeAiUseScript: VideoScript = withNarration(baseScript);
